"""created fk_cargo_oficial_id

Revision ID: 22e37c552410
Revises: f7b0b4c24ae5
Create Date: 2025-03-22 22:26:49.530252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22e37c552410'
down_revision = 'f7b0b4c24ae5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oficiais', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fk_cargo_oficial_id', sa.Uuid(), nullable=True))
        batch_op.create_index(batch_op.f('ix_oficiais_fk_cargo_oficial_id'), ['fk_cargo_oficial_id'], unique=False)
        batch_op.create_foreign_key('FK_cargo_id_KJ89KO', 'cargos_oficiais', ['fk_cargo_oficial_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oficiais', schema=None) as batch_op:
        batch_op.drop_constraint('FK_cargo_id_KJ89KO', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_oficiais_fk_cargo_oficial_id'))
        batch_op.drop_column('fk_cargo_oficial_id')

    # ### end Alembic commands ###
