"""altera modelos de permissões

Revision ID: 2b3b62ab9d6d
Revises: 346d0e69a8a0
Create Date: 2025-06-07 23:24:57.428713

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '2b3b62ab9d6d'
down_revision = '346d0e69a8a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permissoes_lead', schema=None) as batch_op:
        batch_op.add_column(sa.Column('criado_por_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('alterado_por_id', sa.Uuid(), nullable=True))
        batch_op.drop_constraint('FK__permissoe__criad__1F44785D', type_='foreignkey')
        batch_op.drop_constraint('FK__permissoe__alter__1D5C2FEB', type_='foreignkey')
        batch_op.create_foreign_key(None, 'leads', ['alterado_por_id'], ['id'])
        batch_op.create_foreign_key(None, 'leads', ['criado_por_id'], ['id'])
        batch_op.drop_column('alterado_por')
        batch_op.drop_column('criado_por')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permissoes_lead', schema=None) as batch_op:
        batch_op.add_column(sa.Column('criado_por', mssql.UNIQUEIDENTIFIER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('alterado_por', mssql.UNIQUEIDENTIFIER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('FK__permissoe__alter__1D5C2FEB', 'leads', ['alterado_por'], ['id'])
        batch_op.create_foreign_key('FK__permissoe__criad__1F44785D', 'leads', ['criado_por'], ['id'])
        batch_op.drop_column('alterado_por_id')
        batch_op.drop_column('criado_por_id')

    # ### end Alembic commands ###
