"""altera modelo permissaolead para adicionar sistema
Revision ID: 346d0e69a8a0
Revises: fb2d45b85887
Create Date: 2025-06-07 20:04:21.786666
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '346d0e69a8a0'
down_revision = 'fb2d45b85887'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permissoes_lead', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sistema_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('criado_por', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('alterado_por', sa.Uuid(), nullable=True))
        batch_op.create_foreign_key(None, 'leads', ['alterado_por'], ['id'])
        batch_op.create_foreign_key(None, 'sistema', ['sistema_id'], ['id'])
        batch_op.create_foreign_key(None, 'leads', ['criado_por'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permissoes_lead', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('alterado_por')
        batch_op.drop_column('criado_por')
        batch_op.drop_column('sistema_id')
    # ### end Alembic commands ###