"""corrige migrações dos modulo de permissões agape

Revision ID: 634838243ff7
Revises: 2b3b62ab9d6d
Create Date: 2025-06-08 00:32:09.429608

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '634838243ff7'
down_revision = '2b3b62ab9d6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('perfis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('criado_por_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('alterado_por_id', sa.Uuid(), nullable=True))
        batch_op.drop_constraint('FK__perfis__criado_p__1B73E779', type_='foreignkey')
        batch_op.drop_constraint('FK__perfis__alterado__1A7FC340', type_='foreignkey')
        batch_op.create_foreign_key(None, 'leads', ['criado_por_id'], ['id'])
        batch_op.create_foreign_key(None, 'leads', ['alterado_por_id'], ['id'])
        batch_op.drop_column('alterado_por')
        batch_op.drop_column('criado_por')

    with op.batch_alter_table('sistema', schema=None) as batch_op:
        batch_op.add_column(sa.Column('criado_por_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('alterado_por_id', sa.Uuid(), nullable=True))
        batch_op.drop_constraint('FK__sistema__alterad__15BB0E23', type_='foreignkey')
        batch_op.drop_constraint('FK__sistema__criado___16AF325C', type_='foreignkey')
        batch_op.create_foreign_key(None, 'leads', ['alterado_por_id'], ['id'])
        batch_op.create_foreign_key(None, 'leads', ['criado_por_id'], ['id'])
        batch_op.drop_column('alterado_por')
        batch_op.drop_column('criado_por')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sistema', schema=None) as batch_op:
        batch_op.add_column(sa.Column('criado_por', mssql.UNIQUEIDENTIFIER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('alterado_por', mssql.UNIQUEIDENTIFIER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('FK__sistema__criado___16AF325C', 'leads', ['criado_por'], ['id'])
        batch_op.create_foreign_key('FK__sistema__alterad__15BB0E23', 'leads', ['alterado_por'], ['id'])
        batch_op.drop_column('alterado_por_id')
        batch_op.drop_column('criado_por_id')

    with op.batch_alter_table('perfis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('criado_por', mssql.UNIQUEIDENTIFIER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('alterado_por', mssql.UNIQUEIDENTIFIER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('FK__perfis__alterado__1A7FC340', 'leads', ['alterado_por'], ['id'])
        batch_op.create_foreign_key('FK__perfis__criado_p__1B73E779', 'leads', ['criado_por'], ['id'])
        batch_op.drop_column('alterado_por_id')
        batch_op.drop_column('criado_por_id')
    # ### end Alembic commands ###
