"""cria modelo sistema

Revision ID: ab01b04d524f
Revises: 73fefac0cf5c
Create Date: 2025-06-07 19:50:56.295069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab01b04d524f'
down_revision = '73fefac0cf5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sistema',
    sa.Column('nome', sa.String(length=20), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('versao', sa.String(length=15), nullable=False),
    sa.Column('criado_por', sa.Uuid(), nullable=True),
    sa.Column('alterado_por', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['alterado_por'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['criado_por'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sistema')
    # ### end Alembic commands ###
