"""Tabelas do bot de lives

Revision ID: cd1ebe1bfed1
Revises: 218e81c94b9b
Create Date: 2025-04-24 21:21:01.100960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd1ebe1bfed1'
down_revision = '218e81c94b9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lives',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tag', sa.String(length=100), nullable=False),
    sa.Column('fk_campanha_id', sa.Uuid(), nullable=False),
    sa.Column('rede_social', sa.String(length=50), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('criado_por', sa.Uuid(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['criado_por'], ['membros.id'], ),
    sa.ForeignKeyConstraint(['fk_campanha_id'], ['campanhas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audiencia_lives',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fk_live_id', sa.Uuid(), nullable=False),
    sa.Column('titulo', sa.String(length=155), nullable=False),
    sa.Column('audiencia', sa.Integer(), nullable=False),
    sa.Column('data_hora_registro', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fk_live_id'], ['lives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audiencia_lives', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audiencia_lives_fk_live_id'), ['fk_live_id'], unique=False)

    op.create_table('lives_avulsas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fk_live_id', sa.Uuid(), nullable=False),
    sa.Column('data_hora_inicio', sa.DateTime(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('criado_por', sa.Uuid(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['criado_por'], ['membros.id'], ),
    sa.ForeignKeyConstraint(['fk_live_id'], ['lives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lives_avulsas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lives_avulsas_fk_live_id'), ['fk_live_id'], unique=False)

    op.create_table('lives_recorrentes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('dia_semana', sa.String(length=50), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('fk_live_id', sa.Uuid(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('criado_por', sa.Uuid(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['criado_por'], ['membros.id'], ),
    sa.ForeignKeyConstraint(['fk_live_id'], ['lives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lives_recorrentes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lives_recorrentes_fk_live_id'), ['fk_live_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lives_recorrentes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lives_recorrentes_fk_live_id'))

    op.drop_table('lives_recorrentes')
    with op.batch_alter_table('lives_avulsas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lives_avulsas_fk_live_id'))

    op.drop_table('lives_avulsas')
    with op.batch_alter_table('audiencia_lives', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audiencia_lives_fk_live_id'))

    op.drop_table('audiencia_lives')
    op.drop_table('lives')

    # ### end Alembic commands ###
