"""adiciona, slug e sistema no menusistema
Revision ID: cf8a8a3a7046
Revises: ab01b04d524f
Create Date: 2025-06-07 19:52:47.161200
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf8a8a3a7046'
down_revision = 'ab01b04d524f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menus_sistema', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('sistema_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('criado_por', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('alterado_por', sa.Uuid(), nullable=True))
        batch_op.alter_column('nome',
               existing_type=sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'leads', ['alterado_por'], ['id'])
        batch_op.create_foreign_key(None, 'leads', ['criado_por'], ['id'])
        batch_op.create_foreign_key(None, 'sistema', ['sistema_id'], ['id'])
        batch_op.drop_column('descricao')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menus_sistema', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descricao', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('nome',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)
        batch_op.drop_column('alterado_por')
        batch_op.drop_column('criado_por')
        batch_op.drop_column('sistema_id')
        batch_op.drop_column('slug')
    # ### end Alembic commands ###