"""Adicionada coluna de para armazear data de atualização do cadastro

Revision ID: d5ea958175c6
Revises: 3b795b8b6135
Create Date: 2025-03-11 14:21:49.663662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5ea958175c6'
down_revision = '3b795b8b6135'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('membros', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'cadastro_atualizado_em', sa.DateTime(), nullable=True
            )
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('membros', schema=None) as batch_op:
        batch_op.drop_column('cadastro_atualizado_em')


    # ### end Alembic commands ###
