"""alteracoes de backref nos modelos de permissoes
Revision ID: f203d1d0b5b9
Revises: 634838243ff7
Create Date: 2025-06-08 01:09:15.519092
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = 'f203d1d0b5b9'
down_revision = '634838243ff7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menus_sistema', schema=None) as batch_op:
        batch_op.add_column(sa.Column('criado_por_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('alterado_por_id', sa.Uuid(), nullable=True))
        batch_op.drop_constraint('FK__menus_sis__criad__18977ACE', type_='foreignkey')
        batch_op.drop_constraint('FK__menus_sis__alter__17A35695', type_='foreignkey')
        batch_op.create_foreign_key(None, 'leads', ['alterado_por_id'], ['id'])
        batch_op.create_foreign_key(None, 'leads', ['criado_por_id'], ['id'])
        batch_op.drop_column('criado_por')
        batch_op.drop_column('alterado_por')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menus_sistema', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alterado_por', mssql.UNIQUEIDENTIFIER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('criado_por', mssql.UNIQUEIDENTIFIER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('FK__menus_sis__alter__17A35695', 'leads', ['alterado_por'], ['id'])
        batch_op.create_foreign_key('FK__menus_sis__criad__18977ACE', 'leads', ['criado_por'], ['id'])
        batch_op.drop_column('alterado_por_id')
        batch_op.drop_column('criado_por_id')
    # ### end Alembic commands ###