"""delete fk_cargo_oficial_id

Revision ID: f7b0b4c24ae5
Revises: f80b5db04d03
Create Date: 2025-03-22 22:24:36.479096

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = 'f7b0b4c24ae5'
down_revision = 'f80b5db04d03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oficiais', schema=None) as batch_op:
        batch_op.drop_index('ix_oficiais_fk_cargo_oficial_id')
        batch_op.drop_constraint('FK__cargos_ofici__fk_cargos_34KJ8JA', type_='foreignkey')
        batch_op.drop_column('fk_cargo_oficial_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oficiais', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fk_cargo_oficial_id', mssql.UNIQUEIDENTIFIER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('FK__cargos_ofici__fk_cargos_34KJ8JA', 'cargos_oficiais', ['fk_cargo_oficial_id'], ['id'])
        batch_op.create_index('ix_oficiais_fk_cargo_oficial_id', ['fk_cargo_oficial_id'], unique=False)

    # ### end Alembic commands ###
