from enum import Enum


class ExportarDoacoesEnum(str, Enum):  # NOSONAR
    benfeitor_id = 'benfeitor_id'
    nome = 'nome'
    numero_documento = 'numero_documento'
    lead_id = 'lead_id'
    email = 'email'
    telefone = 'telefone'
    pais = 'pais'
    ultimo_acesso = 'ultimo_acesso'
    lead_status = 'lead_status'
    origem_cadastro = 'origem_cadastro'
    membro_id = 'membro_id'
    nome_social = 'nome_social'
    data_nascimento = 'data_nascimento'
    sexo = 'sexo'
    campanha_id = 'campanha_id'
    campanha_nome = 'campanha_nome'
    doacao_id = 'doacao_id'
    doacao_criada_em = 'doacao_criada_em'
    doacao_cancelada_em = 'doacao_cancelada_em'
    pagamento_doacao_id = 'pagamento_doacao_id'
    valor_doacao = 'valor_doacao'
    recorrente = 'recorrente'
    forma_pagamento = 'forma_pagamento'
    codigo_ordem_pagamento = 'codigo_ordem_pagamento'
    anonimo = 'anonimo'
    gateway = 'gateway'
    ativo = 'ativo'
    processamento_doacao_id = 'processamento_doacao_id'
    processado_em = 'processado_em'
    codigo_referencia = 'codigo_referencia'
    codigo_transacao = 'codigo_transacao'
    codigo_comprovante = 'codigo_comprovante'
    nosso_numero = 'nosso_numero'
    status_processamento = 'status_processamento'
