repos:
-   repo: https://gitlab.com/vojko.pribudic.foss/pre-commit-update
    rev: v0.7.0
    hooks:
    -   id: pre-commit-update
        fail_fast: true

-   repo: https://github.com/gitleaks/gitleaks
    rev: v8.27.0
    hooks:
    -   id: gitleaks
        fail_fast: true

-   repo: https://github.com/python-poetry/poetry
    rev: 2.1.3
    hooks:
    -   id: poetry-check
        fail_fast: true
    -   id: poetry-lock
        fail_fast: true
    -   id: poetry-install

-   repo: https://github.com/python-poetry/poetry-plugin-export
    rev: 1.9.0
    hooks:
    -   id: poetry-export
        fail_fast: true

-   repo: local
    hooks:
#     -   id: pytest
#         name: pytest
#         entry: pytest
#         language: system
#         types: [python]
#         args: ["--cov=src", "--cov-report=html", "-p", "no:warnings"]
#         fail_fast: true
#         pass_filenames: false

    -   id: ruff
        name: ruff
        entry: poe
        language: system
        types: [python]
        args: ["format"]
        pass_filenames: false
        fail_fast: true

-   repo: https://github.com/pypa/pip-audit
    rev: v2.9.0
    hooks:
    -   id: pip-audit
        description: "Audits Python environments and dependency trees for known vulnerabilities"
        args: ["-r", "requirements.txt"]
        files: ^(poetry\.lock|pyproject\.toml|poetry\.toml|requirements\.txt)$


ci:
  skip: [pip-audit]
