"""alter_table_users_imports_email

Revision ID: 0036c5c0a5ac
Revises: 31f41250ba88
Create Date: 2024-08-13 11:36:27.472344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0036c5c0a5ac'
down_revision = '31f41250ba88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_imports', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=1010, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=1011),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_imports', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.String(length=1011),
               type_=sa.VARCHAR(length=1010, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)

    # ### end Alembic commands ###
