"""Add_Column_deleted_at_Campaigns

Revision ID: 01376260742f
Revises: f725c96bb641
Create Date: 2024-05-23 15:23:17.781389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01376260742f'
down_revision = 'f725c96bb641'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campanha', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campanha', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    # ### end Alembic commands ###
