"""Create_Table_list_exception_donations

Revision ID: 030c6d00c812
Revises: 35929f7e356e
Create Date: 2024-07-17 12:03:39.991658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '030c6d00c812'
down_revision = '35929f7e356e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('list_exception_donations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_clifor_id', sa.Integer(), nullable=False),
    sa.Column('fk_usuario_id', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=130), nullable=False),
    sa.Column('cpf_cnpj', sa.String(length=20), nullable=True),
    sa.Column('data_inclusao', sa.DateTime(), nullable=True),
    sa.Column('incluido_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_clifor_id'], ['clifor.id'], ),
    sa.ForeignKeyConstraint(['fk_usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('list_exception_donations')
    # ### end Alembic commands ###
