"""add-ponto_referencia-and-index-in-address

Revision ID: 0a5d5f53b68d
Revises: 79c93076bce6
Create Date: 2024-11-22 15:37:30.275703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a5d5f53b68d'
down_revision = '79c93076bce6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('endereco', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ponto_referencia', sa.String(length=100), nullable=True))
        batch_op.create_index(batch_op.f('ix_endereco_cep'), ['cep'], unique=False)
        batch_op.create_index(batch_op.f('ix_endereco_fk_clifor_id'), ['fk_clifor_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('endereco', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_endereco_fk_clifor_id'))
        batch_op.drop_index(batch_op.f('ix_endereco_cep'))
        batch_op.drop_column('ponto_referencia')

    # ### end Alembic commands ###
