"""empty message

Revision ID: 129b27d86f61
Revises: 773917c16bfe
Create Date: 2023-10-12 11:48:10.664513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '129b27d86f61'
down_revision = '773917c16bfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campanha', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chave_pix', sa.String(length=100), nullable=True))

    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('anonimo', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.drop_column('anonimo')

    with op.batch_alter_table('campanha', schema=None) as batch_op:
        batch_op.drop_column('chave_pix')

    # ### end Alembic commands ###
