"""alter_cargo_usuario

Revision ID: 13a454ed79fb
Revises: 37b8917378b3
Create Date: 2024-09-23 15:54:10.322620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13a454ed79fb'
down_revision = '37b8917378b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cargo_usuario', schema=None) as batch_op:
        batch_op.alter_column('convite',
               existing_type=sa.SMALLINT(),
               nullable=True)
        batch_op.alter_column('usuario_criacao',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cargo_usuario', schema=None) as batch_op:
        batch_op.alter_column('usuario_criacao',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('convite',
               existing_type=sa.SMALLINT(),
               nullable=False)

    # ### end Alembic commands ###
