"""alterando-tabelas-viewes

Revision ID: 14a0e04317e0
Revises: 4e4013fa3c22
Create Date: 2024-07-26 13:49:12.664525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14a0e04317e0'
down_revision = '4e4013fa3c22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('view_audiencias', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('titulo', sa.String(length=255), nullable=False))

    with op.batch_alter_table('view_lives', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('tag', sa.String(length=100), nullable=False))
        batch_op.drop_constraint(
            'FK__view_live__fk_vi__4119A21D', type_='foreignkey')
        batch_op.drop_column('fk_view_canal_youtube_id')
        batch_op.drop_column('titulo')

    op.drop_table('view_canais_youtube')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('view_lives', schema=None) as batch_op:
        batch_op.add_column(sa.Column('titulo', sa.VARCHAR(
            length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column(
            'fk_view_canal_youtube_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('FK__view_live__fk_vi__17E28260', 'view_canais_youtube', [
                                    'fk_view_canal_youtube_id'], ['id'])
        batch_op.drop_column('tag')

    with op.batch_alter_table('view_audiencias', schema=None) as batch_op:
        batch_op.drop_column('titulo')

    op.create_table('view_canais_youtube',
                    sa.Column('id', sa.INTEGER(), sa.Identity(
                        always=False, start=1, increment=1), autoincrement=True, nullable=False),
                    sa.Column('tag', sa.VARCHAR(
                        length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint(
                        'id', name='PK__view_can__3213E83F279CD187')
                    )
    # ### end Alembic commands ###
