"""Add_Column_id_user_Users_imports

Revision ID: 186424621830
Revises: 898e3879fad3
Create Date: 2024-04-17 09:50:38.073172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '186424621830'
down_revision = '898e3879fad3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_imports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_user', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_imports', schema=None) as batch_op:
        batch_op.drop_column('id_user')

    # ### end Alembic commands ###
