"""criado coluna super_perfil em perfil e removida coluna super_user em perm_usuario

Revision ID: 1a78a63e81ed
Revises: 307d217bc9e1
Create Date: 2024-04-15 18:49:50.126153

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '1a78a63e81ed'
down_revision = '307d217bc9e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('perfil', schema=None) as batch_op:
        batch_op.add_column(sa.Column('super_perfil', sa.Boolean(), nullable=True))

    with op.batch_alter_table('permissao_usuario', schema=None) as batch_op:
        batch_op.drop_column('super_user')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permissao_usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('super_user', mssql.BIT(), autoincrement=False, nullable=True))

    with op.batch_alter_table('perfil', schema=None) as batch_op:
        batch_op.drop_column('super_perfil')

    # ### end Alembic commands ###
