"""alter_table_users_imports_email

Revision ID: 1aa2cc1086b6
Revises: 0036c5c0a5ac
Create Date: 2024-08-13 11:57:07.699119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1aa2cc1086b6'
down_revision = '0036c5c0a5ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_imports', schema=None) as batch_op:
        op.execute('ALTER TABLE users_imports DROP CONSTRAINT UQ__users_im__AB6E6164084EC4D0;')
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=1011, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=1010),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_imports', schema=None) as batch_op:
        op.create_unique_constraint('UQ__users_im__AB6E6164084EC4D0', 'users_imports', ['email'])
        batch_op.alter_column('email',
               existing_type=sa.String(length=1010),
               type_=sa.VARCHAR(length=1011, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)

    # ### end Alembic commands ###
