"""adicionando index nas tabelas utilizadas em generais

Revision ID: 1b026a1c6682
Revises: 411c226e722b
Create Date: 2025-01-26 05:48:13.172203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b026a1c6682'
down_revision = '411c226e722b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generais', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_generais_fk_cargo_id'), ['fk_cargo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_generais_fk_usuario_id'), ['fk_usuario_id'], unique=False)

    with op.batch_alter_table('landpage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_landpage_campanha_id'), ['campanha_id'], unique=False)

    with op.batch_alter_table('permissao_usuario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permissao_usuario_fk_perfil_id'), ['fk_perfil_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_permissao_usuario_fk_usuario_id'), ['fk_usuario_id'], unique=False)

    with op.batch_alter_table('users_imports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_imports_email'), ['email'], unique=False)

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuario_campanha_origem'), ['campanha_origem'], unique=False)
        batch_op.create_index(batch_op.f('ix_usuario_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_usuario_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuario_email'))
        batch_op.drop_index(batch_op.f('ix_usuario_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_usuario_campanha_origem'))

    with op.batch_alter_table('users_imports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_imports_email'))

    with op.batch_alter_table('permissao_usuario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permissao_usuario_fk_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_permissao_usuario_fk_perfil_id'))

    with op.batch_alter_table('landpage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_landpage_campanha_id'))

    with op.batch_alter_table('generais', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generais_fk_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_generais_fk_cargo_id'))

    # ### end Alembic commands ###
