"""Alter_table_historico_campaign

Revision ID: 1fb9f88d1143
Revises: c794f1ea1f42
Create Date: 2024-08-10 20:58:07.610695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fb9f88d1143'
down_revision = 'c794f1ea1f42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historico_campanha_doacoes', schema=None) as batch_op:
        batch_op.alter_column('valor_meta',
               existing_type=sa.NUMERIC(precision=18, scale=0),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('valor_atingido',
               existing_type=sa.NUMERIC(precision=18, scale=0),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historico_campanha_doacoes', schema=None) as batch_op:
        batch_op.alter_column('valor_atingido',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=18, scale=0),
               existing_nullable=True)
        batch_op.alter_column('valor_meta',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=18, scale=0),
               existing_nullable=True)

    # ### end Alembic commands ###
