"""correcao-migrate-homolog-prod

Revision ID: 2c3b69f42d36
Revises: 545f3a0a6e04
Create Date: 2024-04-22 16:08:30.248745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c3b69f42d36'
down_revision = '545f3a0a6e04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('migrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('migration', sa.UnicodeText(length=255), nullable=False),
    sa.Column('batch', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('logs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('mensagem', sa.UnicodeText(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Integer(), nullable=False),
    sa.Column('acao', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.UnicodeText(length=255), nullable=True))
        batch_op.alter_column('nome',
               existing_type=sa.VARCHAR(length=45, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('nome',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=45, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)
        batch_op.drop_column('country')

    op.drop_table('logs')
    op.drop_table('migrations')
    # ### end Alembic commands ###
