"""Update_table_pedidos_de_oracao

Revision ID: 2cb3a6e7c261
Revises: fe9087c92df1
Create Date: 2024-06-18 11:21:18.821584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cb3a6e7c261'
down_revision = 'fe9087c92df1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos_de_oracao', schema=None) as batch_op:
        batch_op.alter_column('data_realizacao',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos_de_oracao', schema=None) as batch_op:
        batch_op.alter_column('data_realizacao',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
