"""alter table generais

Revision ID: 2e2b534fc738
Revises: 5e4e184eb057
Create Date: 2025-01-23 10:23:31.297391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e2b534fc738'
down_revision = '5e4e184eb057'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generais', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fk_usuario_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('fk_cargo_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('FK__generais__cargo__0D64F3ED', type_='foreignkey')
        batch_op.create_foreign_key(None, 'cargo', ['fk_cargo_id'], ['id'])
        batch_op.create_foreign_key(None, 'usuario', ['fk_usuario_id'], ['id'])
        batch_op.drop_constraint('uq_generais_email', type_='unique')
        batch_op.drop_column('cargo')
        batch_op.drop_column('nome')
        batch_op.drop_column('telefone')
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generais', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('telefone', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('nome', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cargo', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('FK__generais__cargo__0D64F3ED', 'cargo', ['cargo'], ['id'])
        batch_op.drop_column('fk_cargo_id')
        batch_op.drop_column('fk_usuario_id')

    # ### end Alembic commands ###
