"""table_user_perm_super_user_int_to_bool

Revision ID: 307d217bc9e1
Revises: 7084e4f1e741
Create Date: 2024-04-15 16:37:34.864048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '307d217bc9e1'
down_revision = '7084e4f1e741'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permissao_usuario', schema=None) as batch_op:
        batch_op.alter_column('super_user',
               existing_type=sa.SMALLINT(),
               type_=sa.Boolean(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permissao_usuario', schema=None) as batch_op:
        batch_op.alter_column('super_user',
               existing_type=sa.Boolean(),
               type_=sa.SMALLINT(),
               existing_nullable=True)

    # ### end Alembic commands ###
