"""create_table_pre_cadastro_vocacional

Revision ID: 30b2195d04c2
Revises: f5d9b6f304ea
Create Date: 2024-08-23 16:11:44.194099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30b2195d04c2'
down_revision = 'f5d9b6f304ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pre_cadastro_vocacional',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=250), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=True),
    sa.Column('telefone', sa.String(length=19), nullable=True),
    sa.Column('status', sa.String(length=18), nullable=False),
    sa.Column('contatado_em', sa.DateTime(), nullable=True),
    sa.Column('contatado_por', sa.Integer(), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('vocacional', sa.String(length=15), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pre_cadastro_vocacional')
    # ### end Alembic commands ###
