"""empty message

Revision ID: 30c750d7b553
Revises: 1cda7e3e5163
Create Date: 2023-09-06 10:02:14.951213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30c750d7b553'
down_revision = '1cda7e3e5163'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('landpage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campanha_id', sa.Integer(), nullable=True),
    sa.Column('background', sa.String(length=100), nullable=False),
    sa.Column('banner', sa.String(length=100), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=100), nullable=False),
    sa.Column('tipo_cadastro', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('usuario_criacao', sa.Integer(), nullable=False),
    sa.Column('data_alteracao', sa.DateTime(), nullable=True),
    sa.Column('usuario_alteracao', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['campanha_id'], ['campanha.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conteudo_landpage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('landpage_id', sa.Integer(), nullable=False),
    sa.Column('imagem', sa.String(length=100), nullable=False),
    sa.Column('html', sa.UnicodeText(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('usuario_criacao', sa.Integer(), nullable=False),
    sa.Column('data_alteracao', sa.DateTime(), nullable=True),
    sa.Column('usuario_alteracao', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['landpage_id'], ['landpage.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conteudo_landpage')
    op.drop_table('landpage')
    # ### end Alembic commands ###
