"""create-table-leads-sorteados

Revision ID: 31f41250ba88
Revises: 1fb9f88d1143
Create Date: 2024-08-12 18:48:29.199894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31f41250ba88'
down_revision = '1fb9f88d1143'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actions_leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('titulo', sa.Unicode(length=255), nullable=True))
        batch_op.add_column(sa.Column('descricao', sa.UnicodeText(), nullable=True))
        batch_op.add_column(sa.Column('background', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('banner', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('status', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('sorteio', sa.Boolean(), nullable=True))

    with op.batch_alter_table('foto_campanha', schema=None) as batch_op:
        batch_op.drop_constraint('FK__foto_camp__fk_la__5EDF0F2E', type_='foreignkey')
        batch_op.drop_column('fk_landpage_id')

    with op.batch_alter_table('historico_campanha_doacoes', schema=None) as batch_op:
        batch_op.drop_constraint('FK__historico__fk_ca__04459E07', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historico_campanha_doacoes', schema=None) as batch_op:
        batch_op.create_foreign_key('FK__historico__fk_ca__04459E07', 'campanha', ['fk_campanha_id'], ['id'])

    with op.batch_alter_table('foto_campanha', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fk_landpage_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('FK__foto_camp__fk_la__5EDF0F2E', 'landpage', ['fk_landpage_id'], ['id'])

    with op.batch_alter_table('actions_leads', schema=None) as batch_op:
        batch_op.drop_column('sorteio')
        batch_op.drop_column('status')
        batch_op.drop_column('banner')
        batch_op.drop_column('background')
        batch_op.drop_column('descricao')
        batch_op.drop_column('titulo')

    # ### end Alembic commands ###
