"""feat: adicionado tabelas para academia acutis

Revision ID: 333b14e590fc
Revises: e990db62b627
Create Date: 2024-04-10 12:19:27.622451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '333b14e590fc'
down_revision = 'e990db62b627'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('descricao', sa.UnicodeText(), nullable=False),
    sa.Column('imagem', sa.UnicodeText(), nullable=False),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('usuario_criacao', sa.Integer(), nullable=False),
    sa.Column('data_alteracao', sa.DateTime(), nullable=True),
    sa.Column('usuario_alteracao', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_alteracao'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['usuario_criacao'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('modulo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('fk_curso_id', sa.Integer(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('usuario_criacao', sa.Integer(), nullable=False),
    sa.Column('data_alteracao', sa.DateTime(), nullable=True),
    sa.Column('usuario_alteracao', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_curso_id'], ['curso.id'], ),
    sa.ForeignKeyConstraint(['usuario_alteracao'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['usuario_criacao'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aula',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('carga_horaria', sa.Float(), nullable=False),
    sa.Column('link_video', sa.UnicodeText(), nullable=True),
    sa.Column('material_apoio', sa.UnicodeText(), nullable=True),
    sa.Column('texto', sa.UnicodeText(), nullable=True),
    sa.Column('fk_modulo_id', sa.Integer(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('usuario_criacao', sa.Integer(), nullable=False),
    sa.Column('data_alteracao', sa.DateTime(), nullable=True),
    sa.Column('usuario_alteracao', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_modulo_id'], ['modulo.id'], ),
    sa.ForeignKeyConstraint(['usuario_alteracao'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['usuario_criacao'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('progresso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_usuario_id', sa.Integer(), nullable=False),
    sa.Column('fk_aula_id', sa.Integer(), nullable=False),
    sa.Column('iniciado_em', sa.DateTime(), nullable=True),
    sa.Column('concluido_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fk_aula_id'], ['aula.id'], ),
    sa.ForeignKeyConstraint(['fk_usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matricula',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_curso_id', sa.Integer(), nullable=True),
    sa.Column('fk_progresso_id', sa.Integer(), nullable=True),
    sa.Column('matriculado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fk_curso_id'], ['curso.id'], ),
    sa.ForeignKeyConstraint(['fk_progresso_id'], ['progresso.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matricula')
    op.drop_table('progresso')
    op.drop_table('aula')
    op.drop_table('modulo')
    op.drop_table('curso')
    # ### end Alembic commands ###
