"""mpag_doacao_anonima

Revision ID: 35929f7e356e
Revises: 06357e1d4f14
Create Date: 2024-07-16 09:49:25.268039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35929f7e356e'
down_revision = '06357e1d4f14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.alter_column('fk_empresa_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('fk_campanha_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('processamento_pedido', schema=None) as batch_op:
        batch_op.alter_column('fk_empresa_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processamento_pedido', schema=None) as batch_op:
        batch_op.alter_column('fk_empresa_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.alter_column('fk_campanha_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('fk_empresa_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
