"""updated_cargo_usuario

Revision ID: 37b8917378b3
Revises: e84c6b686783
Create Date: 2024-09-23 15:30:16.618590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37b8917378b3'
down_revision = 'e84c6b686783'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cargo_usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quant_membros_grupo', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tempo_de_membro', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('print_grupo', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cargo_usuario', schema=None) as batch_op:
        batch_op.drop_column('print_grupo')
        batch_op.drop_column('tempo_de_membro')
        batch_op.drop_column('quant_membros_grupo')

    # ### end Alembic commands ###
