"""add_unique_constraint_ficha_vocacional

Revision ID: 3c525ca4c353
Revises: 4df9ba997941
Create Date: 2024-09-26 10:27:52.014279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c525ca4c353'
down_revision = '4df9ba997941'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ficha_vocacional', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=15, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.create_unique_constraint(
            'uq_ficha_vocacional_fk_cadastro_vocacional_id',
            ['fk_cadastro_vocacional_id']
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ficha_vocacional', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=15, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)
        
        batch_op.drop_constraint(
            'uq_ficha_vocacional_fk_cadastro_vocacional_id',
            type_='unique'
        )

    # ### end Alembic commands ###
