"""create_table_ficha_vocacional

Revision ID: 3f1f66a480b6
Revises: d663617096e8
Create Date: 2024-08-23 17:14:56.981857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f1f66a480b6'
down_revision = 'd663617096e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ficha_vocacional',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_cadastro_vocacional_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('desistencia_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_por', sa.Integer(), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['fk_cadastro_vocacional_id'], ['cadastro_vocacional.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ficha_vocacional')
    # ### end Alembic commands ###
