"""Alter_Table_Users_Imports

Revision ID: 41a2ab3095da
Revises: 5a6a247e5181
Create Date: 2024-04-17 15:46:57.852611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41a2ab3095da'
down_revision = '5a6a247e5181'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_imports', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=13, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_imports', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=13, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)

    # ### end Alembic commands ###
