"""atualizando migrations

Revision ID: 4c3efc965d98
Revises: ac6f74cd9e1f
Create Date: 2024-04-04 16:23:07.072159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c3efc965d98'
down_revision = 'ac6f74cd9e1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    ...

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('campanha_origem')

    with op.batch_alter_table('landpage_users', schema=None) as batch_op:
        batch_op.alter_column('registered_at',
                              existing_type=sa.DATETIME(),
                              nullable=False)
        batch_op.alter_column('campaign_id',
                              existing_type=sa.INTEGER(),
                              nullable=False)
        batch_op.alter_column('landpage_id',
                              existing_type=sa.INTEGER(),
                              nullable=False)

    with op.batch_alter_table('landpage', schema=None) as batch_op:
        batch_op.alter_column('type',
                              existing_type=sa.INTEGER(),
                              nullable=False,
                              existing_server_default=sa.text("('1')"))

    op.create_table('migrations',
                    sa.Column('id', sa.INTEGER(), sa.Identity(
                        always=False, start=1, increment=1), autoincrement=True, nullable=False),
                    sa.Column('migration', sa.NVARCHAR(length=255),
                              autoincrement=False, nullable=False),
                    sa.Column('batch', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint(
                        'id', name='PK__migratio__3213E83F8819FBA0')
                    )
    op.create_table('logs',
                    sa.Column('id', sa.BIGINT(), sa.Identity(
                        always=False, start=1, increment=1), autoincrement=True, nullable=False),
                    sa.Column('usuario_id', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('mensagem', sa.NVARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('level', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('tipo', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('acao', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('criado_em', sa.DATETIME(),
                              autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(
                        ['usuario_id'], ['usuario.id'], name='logs_usuario_id_foreign'),
                    sa.PrimaryKeyConstraint(
                        'id', name='PK__logs__3213E83F9CC97004')
                    )
    op.drop_table('log_logradouro')
    op.drop_table('log_localidade')
    op.drop_table('log_bairro')
    # ### end Alembic commands ###
