"""add unique contraint in usuario_vocacional

Revision ID: 4d22e8d15436
Revises: 93dd0b3d4077
Create Date: 2025-02-11 15:44:49.912993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d22e8d15436'
down_revision = '93dd0b3d4077'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios_vocacional', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.create_unique_constraint('uq_usuarios_vocacional_email', ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios_vocacional', schema=None) as batch_op:
        batch_op.drop_constraint('uq_usuarios_vocacional_email', type_='unique')
        batch_op.alter_column('email',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)

    # ### end Alembic commands ###
