"""Add unique constraint to email

Revision ID: 4df9ba997941
Revises: a0226b87fc4f
Create Date: 2024-09-25 10:51:13.299882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4df9ba997941'
down_revision = 'a0226b87fc4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generais', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.create_unique_constraint('uq_generais_email', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generais', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
        batch_op.drop_constraint('uq_generais_email', type_='unique')
    # ### end Alembic commands ###
