"""alter_table_users_imports

Revision ID: 510c81c5fe9c
Revises: 4e4edb167d6b
Create Date: 2024-07-31 14:02:30.779815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '510c81c5fe9c'
down_revision = '4e4edb167d6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_imports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('intencao', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_imports', schema=None) as batch_op:
        batch_op.drop_column('intencao')

    # ### end Alembic commands ###
