"""Alter_Column_Users_Imports_size_3

Revision ID: 545f3a0a6e04
Revises: 9c779ec06319
Create Date: 2024-04-18 12:32:31.479868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '545f3a0a6e04'
down_revision = '9c779ec06319'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_imports', schema=None) as batch_op:
        batch_op.alter_column('data_criacao',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=2000),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_imports', schema=None) as batch_op:
        batch_op.alter_column('data_criacao',
               existing_type=sa.String(length=2000),
               type_=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
