"""criado-tabela-foto-leads

Revision ID: 599666132bd5
Revises: fec424444f1e
Create Date: 2024-07-30 15:11:06.751015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '599666132bd5'
down_revision = 'fec424444f1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actions_leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preenchimento_foto', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('label_foto', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actions_leads', schema=None) as batch_op:
        batch_op.drop_column('label_foto')
        batch_op.drop_column('preenchimento_foto')

    # ### end Alembic commands ###
