"""Update_ficha_vocacional

Revision ID: 5caddcd5eab2
Revises: 97e4b1f64ad8
Create Date: 2024-09-20 08:56:50.343326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5caddcd5eab2'
down_revision = '97e4b1f64ad8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ficha_vocacional', schema=None) as batch_op:
        batch_op.add_column(sa.Column('escolaridade', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('profissao', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('cursos', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('sacramentos', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('estado_civil', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('justificativa_divorcio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('referencia_conhecimento_instituto', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('motivacao_admissao_vocacional', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('motivacao_pelo_instituto', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('identificacao_com_instituto', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('rotina_diaria', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('seminario_vida_espirito_santo_realizado_em', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('deixou_religiao_anterior_em', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('aceitacao_familiar', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('problema_saude_descricao', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('remedio_controlado', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('remedio_controlado_data_inicio', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('remedio_controlado_data_fim', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('testemunho_conversao', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('foto_vocacional', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ficha_vocacional', schema=None) as batch_op:
        batch_op.drop_column('foto_vocacional')
        batch_op.drop_column('testemunho_conversao')
        batch_op.drop_column('remedio_controlado_data_fim')
        batch_op.drop_column('remedio_controlado_data_inicio')
        batch_op.drop_column('remedio_controlado')
        batch_op.drop_column('problema_saude_descricao')
        batch_op.drop_column('aceitacao_familiar')
        batch_op.drop_column('deixou_religiao_anterior_em')
        batch_op.drop_column('seminario_vida_espirito_santo_realizado_em')
        batch_op.drop_column('rotina_diaria')
        batch_op.drop_column('identificacao_com_instituto')
        batch_op.drop_column('motivacao_pelo_instituto')
        batch_op.drop_column('motivacao_admissao_vocacional')
        batch_op.drop_column('referencia_conhecimento_instituto')
        batch_op.drop_column('justificativa_divorcio')
        batch_op.drop_column('estado_civil')
        batch_op.drop_column('sacramentos')
        batch_op.drop_column('cursos')
        batch_op.drop_column('profissao')
        batch_op.drop_column('escolaridade')

    # ### end Alembic commands ###
