"""feat: alter table tokens

Revision ID: 5e4e184eb057
Revises: c9a2808f5118
Create Date: 2025-01-22 22:26:19.386393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e4e184eb057'
down_revision = 'c9a2808f5118'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.alter_column('token',
               existing_type=sa.VARCHAR(length=350, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=400),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.alter_column('token',
               existing_type=sa.String(length=400),
               type_=sa.VARCHAR(length=350, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)

    # ### end Alembic commands ###
