"""update_table_evento_usuario

Revision ID: 5fac3a0434cc
Revises: 2c3b69f42d36
Create Date: 2024-04-26 09:54:01.007056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fac3a0434cc'
down_revision = '2c3b69f42d36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evento_usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_register', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evento_usuario', schema=None) as batch_op:
        batch_op.drop_column('data_register')

    # ### end Alembic commands ###
