"""Alter_table-campanha

Revision ID: 60c7abecc68c
Revises: a81b3458c482
Create Date: 2024-05-28 16:54:09.976482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60c7abecc68c'
down_revision = 'a81b3458c482'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campanha', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cadastros_meta', sa.Integer(), nullable=True))

    with op.batch_alter_table('historico_campanha_doacoes', schema=None) as batch_op:
        batch_op.alter_column('valor_meta',
               existing_type=sa.NUMERIC(precision=18, scale=0),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historico_campanha_doacoes', schema=None) as batch_op:
        batch_op.alter_column('valor_meta',
               existing_type=sa.NUMERIC(precision=18, scale=0),
               nullable=False)

    with op.batch_alter_table('campanha', schema=None) as batch_op:
        batch_op.drop_column('cadastros_meta')

    # ### end Alembic commands ###
