"""obriga-atualizar-cadastro

Revision ID: 60d074dbdf09
Revises: b14beef0bc1d
Create Date: 2024-06-22 18:27:35.343983

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '60d074dbdf09'
down_revision = 'b14beef0bc1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('obriga_atualizar_cadastro', sa.Boolean(), nullable=True))
        batch_op.drop_column('obriga_alterar_senha')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('obriga_alterar_senha', mssql.BIT(), autoincrement=False, nullable=True))
        batch_op.drop_column('obriga_atualizar_cadastro')

    # ### end Alembic commands ###
