"""Add contraint unique to fk_usuario_vocacional and documento_identidade in table cadastros_vocacional

Revision ID: 6595ccdd710b
Revises: 4d22e8d15436
Create Date: 2025-02-12 19:20:41.183600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6595ccdd710b'
down_revision = '4d22e8d15436'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cadastros_vocacional', schema=None) as batch_op:
        batch_op.drop_index('ix_cadastros_vocacional_fk_usuario_vocacional_id')
        batch_op.create_index(batch_op.f('ix_cadastros_vocacional_fk_usuario_vocacional_id'), ['fk_usuario_vocacional_id'], unique=True)
        batch_op.create_unique_constraint('uq_cadastros_vocacional_documento_identidade', ['documento_identidade'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cadastros_vocacional', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cadastros_vocacional_fk_usuario_vocacional_id'))
        batch_op.create_index('ix_cadastros_vocacional_fk_usuario_vocacional_id', ['fk_usuario_vocacional_id'], unique=False)
        batch_op.drop_constraint('uq_cadastros_vocacional_documento_identidade', type_='unique')

    # ### end Alembic commands ###
