"""removendo-data-hora-fim-lives

Revision ID: 6bc78801303f
Revises: d39a6ea95aa7
Create Date: 2024-08-29 11:05:12.205867

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '6bc78801303f'
down_revision = 'd39a6ea95aa7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('view_avulsas', schema=None) as batch_op:
        batch_op.drop_column('data_hora_fim')

    with op.batch_alter_table('view_recorrentes', schema=None) as batch_op:
        batch_op.drop_column('data_hora_fim')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('view_recorrentes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_hora_fim', mssql.TIME(), autoincrement=False, nullable=False))

    with op.batch_alter_table('view_avulsas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_hora_fim', sa.DATETIME(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
