"""adicionado coluna programacao acao agape na tabela acao agape

Revision ID: 6bd8b01a5b9b
Revises: 71a71584c008
Create Date: 2025-01-09 12:47:35.790085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bd8b01a5b9b'
down_revision = '71a71584c008'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('acao_agape', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fk_programacao_acao_agape_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_acao_agape_fk_programacao_acao_agape_id'), ['fk_programacao_acao_agape_id'], unique=False)
        batch_op.create_foreign_key(None, 'programacao_acao_agape', ['fk_programacao_acao_agape_id'], ['id'])

    with op.batch_alter_table('programacao_acao_agape', schema=None) as batch_op:
        batch_op.drop_index('ix_programacao_acao_agape_fk_acao_agape_id')
        batch_op.create_index(batch_op.f('ix_programacao_acao_agape_criado_em'), ['criado_em'], unique=False)
        batch_op.drop_constraint('FK__programac__fk_ac__57C7FD4B', type_='foreignkey')
        batch_op.drop_column('fk_acao_agape_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('programacao_acao_agape', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fk_acao_agape_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('FK__programac__fk_ac__57C7FD4B', 'acao_agape', ['fk_acao_agape_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_programacao_acao_agape_criado_em'))
        batch_op.create_index('ix_programacao_acao_agape_fk_acao_agape_id', ['fk_acao_agape_id'], unique=False)

    with op.batch_alter_table('acao_agape', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_acao_agape_fk_programacao_acao_agape_id'))
        batch_op.drop_column('fk_programacao_acao_agape_id')

    # ### end Alembic commands ###
