"""Update_Table-Campaign_Add_Column_duracao

Revision ID: 706f39f5f0f4
Revises: bc3fb6ec3f26
Create Date: 2024-05-08 14:48:16.121217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '706f39f5f0f4'
down_revision = 'bc3fb6ec3f26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campanha', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duracao', sa.String(length=11), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campanha', schema=None) as batch_op:
        batch_op.drop_column('duracao')

    # ### end Alembic commands ###
