"""add-column-id_beneficiario-nosso_numero-processamento-pedido

Revision ID: 706f53299fb5
Revises: 927744230926
Create Date: 2024-05-06 16:23:15.546114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '706f53299fb5'
down_revision = '927744230926'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processamento_pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_beneficiario', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('nosso_numero', sa.String(length=12), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processamento_pedido', schema=None) as batch_op:
        batch_op.drop_column('nosso_numero')
        batch_op.drop_column('id_beneficiario')

    # ### end Alembic commands ###
