"""CreateTableEventoUsuario

Revision ID: 7084e4f1e741
Revises: 333b14e590fc
Create Date: 2024-04-15 09:23:38.805832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7084e4f1e741'
down_revision = '333b14e590fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evento_usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_usuario_id', sa.Integer(), nullable=False),
    sa.Column('fk_campanha_id', sa.Integer(), nullable=False),
    sa.Column('presenca', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['fk_campanha_id'], ['campanha.id'], ),
    sa.ForeignKeyConstraint(['fk_usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evento_usuario')
    # ### end Alembic commands ###
