"""Add foreign key and add column motivo_retorno in mensageria

Revision ID: 71a71584c008
Revises: 1f803bf9a531
Create Date: 2025-01-07 11:46:28.531752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71a71584c008'
down_revision = '1f803bf9a531'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mensageria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fk_tipo_email_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('motivo_retorno', sa.String(length=200), nullable=True))
        batch_op.create_foreign_key(None, 'tipo_email', ['fk_tipo_email_id'], ['id'])
        batch_op.drop_column('tipo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mensageria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('motivo_retorno')
        batch_op.drop_column('fk_tipo_email_id')

    # ### end Alembic commands ###
