"""empty message

Revision ID: 72829eaef9ed
Revises: 129b27d86f61
Create Date: 2023-10-12 11:50:06.773221

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '72829eaef9ed'
down_revision = '129b27d86f61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.alter_column('anonimo',
               existing_type=mssql.BIT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.alter_column('anonimo',
               existing_type=mssql.BIT(),
               nullable=True)

    # ### end Alembic commands ###
