"""criando-tabela-setup-pagamento

Revision ID: 7497296858dc
Revises: 60c7abecc68c
Create Date: 2024-05-29 16:10:25.402398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7497296858dc'
down_revision = '60c7abecc68c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('setup_pagamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credito_unico', sa.Integer(), nullable=True),
    sa.Column('credito_recorrente', sa.Integer(), nullable=True),
    sa.Column('pix_unico', sa.Integer(), nullable=True),
    sa.Column('pix_recorrente', sa.Integer(), nullable=True),
    sa.Column('boleto_unico', sa.Integer(), nullable=True),
    sa.Column('boleto_recorrente', sa.Integer(), nullable=True),
    sa.Column('data_alteracao', sa.DateTime(), nullable=True),
    sa.Column('usuario_alteracao', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['boleto_recorrente'], ['gateway_pagamento.id'], ),
    sa.ForeignKeyConstraint(['boleto_unico'], ['gateway_pagamento.id'], ),
    sa.ForeignKeyConstraint(['credito_recorrente'], ['gateway_pagamento.id'], ),
    sa.ForeignKeyConstraint(['credito_unico'], ['gateway_pagamento.id'], ),
    sa.ForeignKeyConstraint(['pix_recorrente'], ['gateway_pagamento.id'], ),
    sa.ForeignKeyConstraint(['pix_unico'], ['gateway_pagamento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('setup_pagamento')
    # ### end Alembic commands ###
