"""alter_table_foto_campanha

Revision ID: 7964352f58f4
Revises: 80fbbd37484b
Create Date: 2024-06-27 10:25:36.518789

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '7964352f58f4'
down_revision = '80fbbd37484b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foto_campanha', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fk_landpage_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'landpage', ['fk_landpage_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    with op.batch_alter_table('foto_campanha', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('fk_landpage_id')

    # ### end Alembic commands ###
