"""remove-nullable-fk_sistema_id-in-profile

Revision ID: 79c93076bce6
Revises: d36cf86627e0
Create Date: 2024-11-22 12:02:17.857246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79c93076bce6'
down_revision = 'd36cf86627e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('perfil', schema=None) as batch_op:
        batch_op.alter_column('fk_sistema_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('perfil', schema=None) as batch_op:
        batch_op.alter_column('fk_sistema_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
