"""Alter_table_foto_leads

Revision ID: 79fa57ecabe9
Revises: fcc9ce5a2bb8
Create Date: 2024-08-03 12:13:19.011551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79fa57ecabe9'
down_revision = 'fcc9ce5a2bb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foto_leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_download', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foto_leads', schema=None) as batch_op:
        batch_op.drop_column('user_download')

    # ### end Alembic commands ###
