"""campanha-landing-page

Revision ID: 7dbcb2f52fde
Revises: 7964352f58f4
Create Date: 2024-06-27 13:56:09.716093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dbcb2f52fde'
down_revision = '7964352f58f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campanha', schema=None) as batch_op:
        batch_op.alter_column('chave_pix',
                              existing_type=sa.VARCHAR(
                                  length=100, collation='SQL_Latin1_General_CP1_CI_AS'),
                              nullable=True)

    # with op.batch_alter_table('foto_campanha', schema=None) as batch_op:
    #     batch_op.drop_constraint('FK__foto_camp__fk_la__3D491139', type_='foreignkey')
    #     batch_op.drop_column('fk_landpage_id')

    with op.batch_alter_table('setup_pagamento', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('fk_campanha_id', sa.Integer(), nullable=True))
        batch_op.add_column(
            sa.Column('data_criacao', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('usuario_criacao',
                            sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            None, 'campanha', ['fk_campanha_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('setup_pagamento', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('usuario_criacao')
        batch_op.drop_column('data_criacao')
        batch_op.drop_column('fk_campanha_id')

    with op.batch_alter_table('foto_campanha', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('fk_landpage_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('FK__foto_camp__fk_la__3D491139', 'landpage', [
                                    'fk_landpage_id'], ['id'])

    with op.batch_alter_table('campanha', schema=None) as batch_op:
        batch_op.alter_column('chave_pix',
                              existing_type=sa.VARCHAR(
                                  length=100, collation='SQL_Latin1_General_CP1_CI_AS'),
                              nullable=False)

    # ### end Alembic commands ###
