"""Add_Column_users_imports

Revision ID: 7dd1717fe213
Revises: c39dbbeb40f8
Create Date: 2024-05-24 10:57:17.033562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dd1717fe213'
down_revision = 'c39dbbeb40f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_imports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('origem_cadastro', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_imports', schema=None) as batch_op:
        batch_op.drop_column('origem_cadastro')

    # ### end Alembic commands ###
