"""Alter_table_pre_cadastro

Revision ID: 7ed4c045aed3
Revises: a8851f164501
Create Date: 2024-08-27 16:14:45.483455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ed4c045aed3'
down_revision = 'a8851f164501'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pre_cadastro_vocacional', schema=None) as batch_op:
        batch_op.alter_column('etapa',
               existing_type=sa.VARCHAR(length=15, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=27),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pre_cadastro_vocacional', schema=None) as batch_op:
        batch_op.alter_column('etapa',
               existing_type=sa.String(length=27),
               type_=sa.VARCHAR(length=15, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)

    # ### end Alembic commands ###
