"""Alter_table_evento_usuario

Revision ID: 80fbbd37484b
Revises: 970a49efa8d0
Create Date: 2024-06-26 10:22:01.082606

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '80fbbd37484b'
down_revision = '970a49efa8d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evento_usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fk_landpage_id', sa.Integer(), nullable=True))
        batch_op.alter_column('fk_campanha_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'landpage', ['fk_landpage_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evento_usuario', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('fk_campanha_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('fk_landpage_id')

    # ### end Alembic commands ###
