"""Create_Table_Usuarios_Imports

Revision ID: 898e3879fad3
Revises: 1a78a63e81ed
Create Date: 2024-04-16 21:58:30.230779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '898e3879fad3'
down_revision = '1a78a63e81ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_imports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('country', sa.UnicodeText(length=255), nullable=True),
    sa.Column('phone', sa.String(length=13), nullable=True),
    sa.Column('data_nascimento', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_imports')
    # ### end Alembic commands ###
