"""add_nullable_landpage

Revision ID: 898ff235b279
Revises: 3c525ca4c353
Create Date: 2024-09-26 12:54:11.572655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '898ff235b279'
down_revision = '3c525ca4c353'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('landpage', schema=None) as batch_op:
        batch_op.alter_column('background',
               existing_type=sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('landpage', schema=None) as batch_op:
        batch_op.alter_column('background',
               existing_type=sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)

    # ### end Alembic commands ###
