"""create-table-foto-campanha

Revision ID: 89f9693b15f1
Revises: d2f96c4acca9
Create Date: 2024-06-21 18:09:00.000542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89f9693b15f1'
down_revision = 'd2f96c4acca9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('foto_campanha',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_campanha_id', sa.Integer(), nullable=True),
    sa.Column('fk_usuario_id', sa.Integer(), nullable=True),
    sa.Column('foto', sa.String(length=100), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('usuario_criacao', sa.Integer(), nullable=False),
    sa.Column('data_alteracao', sa.DateTime(), nullable=True),
    sa.Column('usuario_alteracao', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_campanha_id'], ['campanha.id'], ),
    sa.ForeignKeyConstraint(['fk_usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('foto_campanha')
    # ### end Alembic commands ###
