"""action-leads-add-column-cadastrado-por

Revision ID: 8ae3267d604c
Revises: e5ff39903db8
Create Date: 2024-08-14 16:45:36.540592

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8ae3267d604c"
down_revision = "e5ff39903db8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("actions_leads", schema=None) as batch_op:
        batch_op.add_column(sa.Column("cadastrado_por", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, "usuario", ["cadastrado_por"], ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("leads_sorteados", schema=None) as batch_op:
        batch_op.alter_column(
            "email",
            existing_type=sa.String(),
            type_=sa.NVARCHAR(length=255),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "nome",
            existing_type=sa.String(),
            type_=sa.NVARCHAR(length=255),
            existing_nullable=True,
        )

    with op.batch_alter_table("actions_leads", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("cadastrado_por")

    # ### end Alembic commands ###
