"""Alter_Table_UsersImports

Revision ID: 8b9abc364e7e
Revises: 186424621830
Create Date: 2024-04-17 12:08:53.693935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b9abc364e7e'
down_revision = '186424621830'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_imports', schema=None) as batch_op:
        batch_op.alter_column('data_nascimento',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_imports', schema=None) as batch_op:
        batch_op.alter_column('data_nascimento',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
