"""Update_table_pedido_de_oracao_add_column_usuario_criacao

Revision ID: 8d2b808d3d46
Revises: b620f75d5998
Create Date: 2024-06-19 11:04:44.150786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d2b808d3d46'
down_revision = 'b620f75d5998'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos_de_oracao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fk_usuario_criacao', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'usuario', ['fk_usuario_criacao'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos_de_oracao', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('fk_usuario_criacao')

    # ### end Alembic commands ###
