"""add-index-em-pagamentos

Revision ID: 8f372bf12ee4
Revises: 6ca8a02848f4
Create Date: 2024-11-14 11:57:53.602149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f372bf12ee4'
down_revision = '6ca8a02848f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clifor', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clifor_cpf_cnpj'), ['cpf_cnpj'], unique=False)
        batch_op.create_index(batch_op.f('ix_clifor_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_clifor_fk_usuario_id'), ['fk_usuario_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clifor_nome'), ['nome'], unique=False)
        batch_op.create_index(batch_op.f('ix_clifor_status'), ['status'], unique=False)

    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pedido_contabilizar_doacao'), ['contabilizar_doacao'], unique=False)
        batch_op.create_index(batch_op.f('ix_pedido_data_pedido'), ['data_pedido'], unique=False)
        batch_op.create_index(batch_op.f('ix_pedido_fk_campanha_id'), ['fk_campanha_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pedido_fk_clifor_id'), ['fk_clifor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pedido_fk_forma_pagamento_id'), ['fk_forma_pagamento_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pedido_fk_gateway_pagamento_id'), ['fk_gateway_pagamento_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pedido_periodicidade'), ['periodicidade'], unique=False)
        batch_op.create_index(batch_op.f('ix_pedido_recorrencia_ativa'), ['recorrencia_ativa'], unique=False)
        batch_op.create_index(batch_op.f('ix_pedido_status_pedido'), ['status_pedido'], unique=False)

    with op.batch_alter_table('processamento_pedido', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_processamento_pedido_contabilizar_doacao'), ['contabilizar_doacao'], unique=False)
        batch_op.create_index(batch_op.f('ix_processamento_pedido_fk_clifor_id'), ['fk_clifor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_processamento_pedido_fk_forma_pagamento_id'), ['fk_forma_pagamento_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_processamento_pedido_fk_pedido_id'), ['fk_pedido_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_processamento_pedido_status_processamento'), ['status_processamento'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processamento_pedido', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_processamento_pedido_status_processamento'))
        batch_op.drop_index(batch_op.f('ix_processamento_pedido_fk_pedido_id'))
        batch_op.drop_index(batch_op.f('ix_processamento_pedido_fk_forma_pagamento_id'))
        batch_op.drop_index(batch_op.f('ix_processamento_pedido_fk_clifor_id'))
        batch_op.drop_index(batch_op.f('ix_processamento_pedido_contabilizar_doacao'))

    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pedido_status_pedido'))
        batch_op.drop_index(batch_op.f('ix_pedido_recorrencia_ativa'))
        batch_op.drop_index(batch_op.f('ix_pedido_periodicidade'))
        batch_op.drop_index(batch_op.f('ix_pedido_fk_gateway_pagamento_id'))
        batch_op.drop_index(batch_op.f('ix_pedido_fk_forma_pagamento_id'))
        batch_op.drop_index(batch_op.f('ix_pedido_fk_clifor_id'))
        batch_op.drop_index(batch_op.f('ix_pedido_fk_campanha_id'))
        batch_op.drop_index(batch_op.f('ix_pedido_data_pedido'))
        batch_op.drop_index(batch_op.f('ix_pedido_contabilizar_doacao'))

    with op.batch_alter_table('clifor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clifor_status'))
        batch_op.drop_index(batch_op.f('ix_clifor_nome'))
        batch_op.drop_index(batch_op.f('ix_clifor_fk_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_clifor_email'))
        batch_op.drop_index(batch_op.f('ix_clifor_cpf_cnpj'))

    # ### end Alembic commands ###
