"""add-col-vencimento-cartao-tab-pedidos

Revision ID: 927744230926
Revises: 5fac3a0434cc
Create Date: 2024-04-30 16:35:28.873730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '927744230926'
down_revision = '5fac3a0434cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vencimento_cartao', sa.String(length=7), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.drop_column('vencimento_cartao')

    # ### end Alembic commands ###
