"""Alter model vocacional

Revision ID: 93dd0b3d4077
Revises: 5998e9740905
Create Date: 2025-02-11 12:19:22.670079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93dd0b3d4077'
down_revision = '5998e9740905'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios_vocacional',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('telefone', sa.String(length=30), nullable=False),
    sa.Column('genero', sa.String(length=10), nullable=False),
    sa.Column('pais', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios_vocacional', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_vocacional_genero'), ['genero'], unique=False)

    op.create_table('fichas_vocacional',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_usuario_vocacional_id', sa.Integer(), nullable=False),
    sa.Column('motivacao_instituto', sa.String(length=255), nullable=False),
    sa.Column('motivacao_admissao_vocacional', sa.String(length=255), nullable=False),
    sa.Column('referencia_conhecimento_instituto', sa.String(length=255), nullable=False),
    sa.Column('identificacao_instituto', sa.String(length=255), nullable=False),
    sa.Column('foto_vocacional', sa.String(length=100), nullable=False),
    sa.Column('seminario_realizado_em', sa.Date(), nullable=False),
    sa.Column('testemunho_conversao', sa.String(length=255), nullable=False),
    sa.Column('escolaridade', sa.String(length=100), nullable=False),
    sa.Column('profissao', sa.String(length=100), nullable=False),
    sa.Column('cursos', sa.String(length=255), nullable=True),
    sa.Column('rotina_diaria', sa.String(length=255), nullable=False),
    sa.Column('aceitacao_familiar', sa.String(length=255), nullable=False),
    sa.Column('estado_civil', sa.String(length=20), nullable=False),
    sa.Column('motivo_divorcio', sa.String(length=255), nullable=True),
    sa.Column('deixou_religiao_anterior_em', sa.Date(), nullable=True),
    sa.Column('remedio_controlado_inicio', sa.Date(), nullable=True),
    sa.Column('remedio_controlado_termino', sa.Date(), nullable=True),
    sa.Column('descricao_problema_saude', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fk_usuario_vocacional_id'], ['usuarios_vocacional.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fichas_vocacional', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fichas_vocacional_fk_usuario_vocacional_id'), ['fk_usuario_vocacional_id'], unique=False)

    op.create_table('sacramentos_vocacional',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_ficha_vocacional_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fk_ficha_vocacional_id'], ['fichas_vocacional.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sacramentos_vocacional', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sacramentos_vocacional_fk_ficha_vocacional_id'), ['fk_ficha_vocacional_id'], unique=False)

    op.create_table('etapas_vocacional',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_usuario_vocacional_id', sa.Integer(), nullable=False),
    sa.Column('etapa', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('justificativa', sa.Text(), nullable=True),
    sa.Column('responsavel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fk_usuario_vocacional_id'], ['usuarios_vocacional.id'], ),
    sa.ForeignKeyConstraint(['responsavel'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('etapas_vocacional', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_etapas_vocacional_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_etapas_vocacional_etapa'), ['etapa'], unique=False)
        batch_op.create_index(batch_op.f('ix_etapas_vocacional_fk_usuario_vocacional_id'), ['fk_usuario_vocacional_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_etapas_vocacional_responsavel'), ['responsavel'], unique=False)
        batch_op.create_index(batch_op.f('ix_etapas_vocacional_status'), ['status'], unique=False)

    op.create_table('cadastros_vocacional',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_usuario_vocacional_id', sa.Integer(), nullable=False),
    sa.Column('fk_endereco_id', sa.Integer(), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('documento_identidade', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fk_endereco_id'], ['endereco.id'], ),
    sa.ForeignKeyConstraint(['fk_usuario_vocacional_id'], ['usuarios_vocacional.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cadastros_vocacional', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cadastros_vocacional_fk_endereco_id'), ['fk_endereco_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cadastros_vocacional_fk_usuario_vocacional_id'), ['fk_usuario_vocacional_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cadastros_vocacional', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cadastros_vocacional_fk_usuario_vocacional_id'))
        batch_op.drop_index(batch_op.f('ix_cadastros_vocacional_fk_endereco_id'))

    op.drop_table('cadastros_vocacional')
    with op.batch_alter_table('etapas_vocacional', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_etapas_vocacional_status'))
        batch_op.drop_index(batch_op.f('ix_etapas_vocacional_responsavel'))
        batch_op.drop_index(batch_op.f('ix_etapas_vocacional_fk_usuario_vocacional_id'))
        batch_op.drop_index(batch_op.f('ix_etapas_vocacional_etapa'))
        batch_op.drop_index(batch_op.f('ix_etapas_vocacional_created_at'))

    op.drop_table('etapas_vocacional')
    with op.batch_alter_table('sacramentos_vocacional', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sacramentos_vocacional_fk_ficha_vocacional_id'))

    op.drop_table('sacramentos_vocacional')
    with op.batch_alter_table('fichas_vocacional', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fichas_vocacional_fk_usuario_vocacional_id'))

    op.drop_table('fichas_vocacional')
    with op.batch_alter_table('usuarios_vocacional', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_vocacional_genero'))

    op.drop_table('usuarios_vocacional')
    # ### end Alembic commands ###
