"""Update_Table_Historico_Doacoes

Revision ID: 953e093dcf57
Revises: abae2a236e1d
Create Date: 2024-05-15 09:15:56.337340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '953e093dcf57'
down_revision = 'abae2a236e1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historico_campanha_doacoes', schema=None) as batch_op:
        batch_op.alter_column('mes_ano',
               existing_type=sa.DATETIME(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.drop_constraint('FK__historico__fk_ca__269AB60B', type_='foreignkey')
        batch_op.create_foreign_key(None, 'campanha', ['fk_campanha_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historico_campanha_doacoes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('FK__historico__fk_ca__269AB60B', 'campanha', ['fk_campanha_id'], ['id'])
        batch_op.alter_column('mes_ano',
               existing_type=sa.String(),
               type_=sa.DATETIME(),
               existing_nullable=False)

    # ### end Alembic commands ###
