"""Alter_Table_Campanha

Revision ID: 955df075f8e0
Revises: a5bc2dbdd73c
Create Date: 2024-10-23 10:51:47.234355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '955df075f8e0'
down_revision = 'a5bc2dbdd73c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campanha', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contabilizar_doacoes', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campanha', schema=None) as batch_op:
        batch_op.drop_column('contabilizar_doacoes')

    # ### end Alembic commands ###
