"""Create_table_pedidos_de_oracao

Revision ID: 96fdf79005eb
Revises: d97366b52240
Create Date: 2024-06-18 10:37:53.371299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96fdf79005eb'
down_revision = 'd97366b52240'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pedidos_de_oracao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('autor', sa.Text(), nullable=False),
    sa.Column('destinado', sa.Text(), nullable=False),
    sa.Column('dados_publicos', sa.Boolean(), nullable=False),
    sa.Column('descricao_pedido', sa.Text(), nullable=False),
    sa.Column('leitura_publica', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('local_realizacao', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('data_realizacao', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pedidos_de_oracao')
    # ### end Alembic commands ###
