"""contabilizar-doacao

Revision ID: 970a49efa8d0
Revises: 60d074dbdf09
Create Date: 2024-06-25 08:23:16.189758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '970a49efa8d0'
down_revision = '60d074dbdf09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contabilizar_doacao', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.drop_column('contabilizar_doacao')

    # ### end Alembic commands ###
