"""Create_table_Mensageria

Revision ID: 9d5a0c93cb39
Revises: bd96af13b2f3
Create Date: 2024-10-30 09:44:45.297369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d5a0c93cb39'
down_revision = 'bd96af13b2f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mensageria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sg_message_id', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mensageria', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mensageria_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_mensageria_sg_message_id'), ['sg_message_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mensageria', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mensageria_sg_message_id'))
        batch_op.drop_index(batch_op.f('ix_mensageria_email'))

    op.drop_table('mensageria')
    # ### end Alembic commands ###
