"""alter_table_action_leads

Revision ID: 9e5fdac9c651
Revises: c26ecdb982bf
Create Date: 2024-07-24 11:50:26.117661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e5fdac9c651'
down_revision = 'c26ecdb982bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actions_leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('create_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actions_leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_at', sa.DATETIME(), autoincrement=False, nullable=True))
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
