"""alter_table_generais

Revision ID: a0226b87fc4f
Revises: 85a20136eaa8
Create Date: 2024-09-23 17:33:33.414405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0226b87fc4f'
down_revision = '85a20136eaa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generais', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fk_usuario_superior_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cargo', sa.Integer(), nullable=True))
        batch_op.drop_constraint('FK__generais__vincul__0B7CAB7B', type_='foreignkey')
        batch_op.create_foreign_key(None, 'cargo', ['cargo'], ['id'])
        batch_op.drop_column('vinculo_marechal')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generais', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vinculo_marechal', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('FK__generais__vincul__0B7CAB7B', 'cargo', ['vinculo_marechal'], ['id'])
        batch_op.drop_column('cargo')
        batch_op.drop_column('fk_usuario_superior_id')

    # ### end Alembic commands ###
