"""add: processamento_pedido/data_lembrete_doacao lembrete_enviado_por

Revision ID: a5bc2dbdd73c
Revises: e3e17fb6c293
Create Date: 2024-10-22 14:37:10.660925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5bc2dbdd73c'
down_revision = 'e3e17fb6c293'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processamento_pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_lembrete_doacao', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('lembrete_enviado_por', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'usuario', ['lembrete_enviado_por'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processamento_pedido', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('lembrete_enviado_por')
        batch_op.drop_column('data_lembrete_doacao')

    # ### end Alembic commands ###
