"""Alter_table_campanha

Revision ID: a81b3458c482
Revises: 7dd1717fe213
Create Date: 2024-05-28 09:52:14.824635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a81b3458c482'
down_revision = '7dd1717fe213'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campanha', schema=None) as batch_op:
        batch_op.add_column(sa.Column('objetivo', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campanha', schema=None) as batch_op:
        batch_op.drop_column('objetivo')

    # ### end Alembic commands ###
