"""update_table_pre_cadastro

Revision ID: a8851f164501
Revises: fe5b599e299b
Create Date: 2024-08-26 11:15:39.793503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8851f164501'
down_revision = 'fe5b599e299b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pre_cadastro_vocacional', schema=None) as batch_op:
        batch_op.add_column(sa.Column('etapa', sa.String(length=15), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pre_cadastro_vocacional', schema=None) as batch_op:
        batch_op.drop_column('etapa')

    # ### end Alembic commands ###
