"""Add_Columns_Table_Historico_Campanha_Doacoes

Revision ID: abae2a236e1d
Revises: 399de65f932d
Create Date: 2024-05-08 17:05:04.303599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abae2a236e1d'
down_revision = '399de65f932d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historico_campanha_doacoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_alteracao', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('usuario_alteracao_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'usuario', ['usuario_alteracao_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historico_campanha_doacoes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('usuario_alteracao_id')
        batch_op.drop_column('data_alteracao')

    # ### end Alembic commands ###
