"""empty message

Revision ID: ac10a4c6c6c4
Revises: fb24475b02ab
Create Date: 2023-10-24 12:07:40.755698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac10a4c6c6c4'
down_revision = 'fb24475b02ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.alter_column('fk_filial_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('processamento_pedido', schema=None) as batch_op:
        batch_op.alter_column('fk_filial_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processamento_pedido', schema=None) as batch_op:
        batch_op.alter_column('fk_filial_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.alter_column('fk_filial_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
