"""empty message

Revision ID: ac6f74cd9e1f
Revises: 3ee272b5d2f5
Create Date: 2024-04-04 16:19:20.793976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac6f74cd9e1f'
down_revision = '3ee272b5d2f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log_bairro',
                    sa.Column('bai_nu', sa.Integer(), nullable=False),
                    sa.Column('ufe_sg', sa.String(length=2), nullable=False),
                    sa.Column('loc_nu', sa.Integer(), nullable=False),
                    sa.Column('bai_no', sa.String(length=72), nullable=False),
                    sa.Column('bai_no_abrev', sa.String(
                        length=36), nullable=True),
                    sa.PrimaryKeyConstraint('bai_nu')
                    )
    op.create_table('log_localidade',
                    sa.Column('loc_nu', sa.Integer(), nullable=False),
                    sa.Column('ufe_sg', sa.String(length=2), nullable=True),
                    sa.Column('loc_no', sa.String(length=72), nullable=True),
                    sa.Column('cep', sa.String(length=8), nullable=True),
                    sa.Column('loc_in_sit', sa.String(
                        length=1), nullable=True),
                    sa.Column('loc_in_tipo_loc', sa.String(
                        length=1), nullable=True),
                    sa.Column('loc_nu_sub', sa.Integer(), nullable=True),
                    sa.Column('loc_no_abrev', sa.String(
                        length=36), nullable=True),
                    sa.Column('mun_nu', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('loc_nu')
                    )
    op.create_table('log_logradouro',
                    sa.Column('log_nu', sa.Integer(), nullable=False),
                    sa.Column('ufe_sg', sa.String(length=2), nullable=True),
                    sa.Column('loc_nu', sa.Integer(), nullable=True),
                    sa.Column('bai_nu_ini', sa.Integer(), nullable=True),
                    sa.Column('bai_nu_fim', sa.Integer(), nullable=True),
                    sa.Column('log_no', sa.String(length=100), nullable=True),
                    sa.Column('log_complemento', sa.String(
                        length=100), nullable=True),
                    sa.Column('cep', sa.String(length=8), nullable=True),
                    sa.Column('tlo_tx', sa.String(length=36), nullable=True),
                    sa.Column('log_sta_tlo', sa.String(
                        length=1), nullable=True),
                    sa.Column('log_no_abrev', sa.String(
                        length=36), nullable=True),
                    sa.PrimaryKeyConstraint('log_nu')
                    )
    op.drop_table('migrations')
    op.drop_table('logs')
    with op.batch_alter_table('landpage', schema=None) as batch_op:
        batch_op.alter_column('type',
                              existing_type=sa.INTEGER(),
                              nullable=True,
                              existing_server_default=sa.text("('1')"))

    with op.batch_alter_table('landpage_users', schema=None) as batch_op:
        batch_op.alter_column('landpage_id',
                              existing_type=sa.INTEGER(),
                              nullable=True)
        batch_op.alter_column('campaign_id',
                              existing_type=sa.INTEGER(),
                              nullable=True)
        batch_op.alter_column('registered_at',
                              existing_type=sa.DATETIME(),
                              nullable=True)

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('campanha_origem',
                            sa.String(), nullable=True))
        batch_op.alter_column('nome',
                              existing_type=sa.NVARCHAR(length=100),
                              type_=sa.String(length=45),
                              existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('nome',
                              existing_type=sa.String(length=45),
                              type_=sa.NVARCHAR(length=100),
                              existing_nullable=False)
        batch_op.drop_column('campanha_origem')

    with op.batch_alter_table('landpage_users', schema=None) as batch_op:
        batch_op.alter_column('registered_at',
                              existing_type=sa.DATETIME(),
                              nullable=False)
        batch_op.alter_column('campaign_id',
                              existing_type=sa.INTEGER(),
                              nullable=False)
        batch_op.alter_column('landpage_id',
                              existing_type=sa.INTEGER(),
                              nullable=False)

    with op.batch_alter_table('landpage', schema=None) as batch_op:
        batch_op.alter_column('type',
                              existing_type=sa.INTEGER(),
                              nullable=False,
                              existing_server_default=sa.text("('1')"))

    op.create_table('logs',
                    sa.Column('id', sa.BIGINT(), sa.Identity(
                        always=False, start=1, increment=1), autoincrement=True, nullable=False),
                    sa.Column('usuario_id', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('mensagem', sa.NVARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('level', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('tipo', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('acao', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('criado_em', sa.DATETIME(),
                              autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(
                        ['usuario_id'], ['usuario.id'], name='logs_usuario_id_foreign'),
                    sa.PrimaryKeyConstraint(
                        'id', name='PK__logs__3213E83F9CC97004')
                    )
    op.create_table('migrations',
                    sa.Column('id', sa.INTEGER(), sa.Identity(
                        always=False, start=1, increment=1), autoincrement=True, nullable=False),
                    sa.Column('migration', sa.NVARCHAR(length=255),
                              autoincrement=False, nullable=False),
                    sa.Column('batch', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint(
                        'id', name='PK__migratio__3213E83F8819FBA0')
                    )
    op.drop_table('log_logradouro')
    op.drop_table('log_localidade')
    op.drop_table('log_bairro')
    # ### end Alembic commands ###
