"""Updated_table_pre_cadastro

Revision ID: ae57ee4bcb46
Revises: 6bc78801303f
Create Date: 2024-08-30 12:21:51.279152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae57ee4bcb46'
down_revision = '6bc78801303f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pre_cadastro_vocacional', schema=None) as batch_op:
        batch_op.add_column(sa.Column('desistencia_em', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pre_cadastro_vocacional', schema=None) as batch_op:
        batch_op.drop_column('desistencia_em')

    # ### end Alembic commands ###
