"""empty message

Revision ID: af3a6f7dff12
Revises: ac10a4c6c6c4
Create Date: 2023-11-16 10:37:21.653066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af3a6f7dff12'
down_revision = 'ac10a4c6c6c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recorrencia_ativa', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.drop_column('recorrencia_ativa')

    # ### end Alembic commands ###
