"""empty message

Revision ID: b05868157641
Revises: 28aad0e6f633
Create Date: 2023-10-13 11:44:57.890643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b05868157641'
down_revision = '28aad0e6f633'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campanha', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chave_pix', sa.String(length=100), nullable=False))

    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('anonimo', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.drop_column('anonimo')

    with op.batch_alter_table('campanha', schema=None) as batch_op:
        batch_op.drop_column('chave_pix')

    # ### end Alembic commands ###
