"""alter table pedido

Revision ID: b4173705bb7b
Revises: 0f041ed55c38
Create Date: 2025-02-21 16:47:19.584549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4173705bb7b'
down_revision = '0f041ed55c38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cancelada_por', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.drop_column('cancelada_por')

    # ### end Alembic commands ###
