"""Update_table_pedidos_de_oracao

Revision ID: b620f75d5998
Revises: 2cb3a6e7c261
Create Date: 2024-06-18 11:24:40.398706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b620f75d5998'
down_revision = '2cb3a6e7c261'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos_de_oracao', schema=None) as batch_op:
        batch_op.alter_column('leitura_publica',
               existing_type=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.Boolean(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos_de_oracao', schema=None) as batch_op:
        batch_op.alter_column('leitura_publica',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)

    # ### end Alembic commands ###
