"""empty message

Revision ID: b810e1412c69
Revises: 
Create Date: 2023-08-28 13:59:40.385694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b810e1412c69'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banco',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('num_banco', sa.String(length=3), nullable=False),
    sa.Column('nome', sa.String(length=40), nullable=True),
    sa.Column('nome_reduzido', sa.String(length=20), nullable=True),
    sa.Column('numero_oficial', sa.String(length=3), nullable=False),
    sa.Column('digito_banco', sa.String(length=1), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('usuario_criacao', sa.Integer(), nullable=False),
    sa.Column('data_alteracao', sa.DateTime(), nullable=True),
    sa.Column('usuario_alteracao', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('banco', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_banco_num_banco'), ['num_banco'], unique=True)

    op.create_table('cargo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('superior', sa.Integer(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('usuario_criacao', sa.Integer(), nullable=False),
    sa.Column('data_alteracao', sa.DateTime(), nullable=True),
    sa.Column('usuario_alteracao', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['superior'], ['cargo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cod_pais', sa.String(length=5), nullable=False),
    sa.Column('nome', sa.String(length=60), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('usuario_criacao', sa.Integer(), nullable=False),
    sa.Column('data_alteracao', sa.DateTime(), nullable=True),
    sa.Column('usuario_alteracao', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sistema',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_sistema', sa.String(length=20), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('versao', sa.String(length=15), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('usuario_criacao', sa.Integer(), nullable=False),
    sa.Column('data_alteracao', sa.DateTime(), nullable=True),
    sa.Column('usuario_alteracao', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tokens_token'), ['token'], unique=False)

    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=45), nullable=False),
    sa.Column('nome_social', sa.String(length=45), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('data_inicio', sa.DateTime(), nullable=True),
    sa.Column('data_expiracao', sa.DateTime(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('obriga_alterar_senha', sa.Boolean(), nullable=True),
    sa.Column('data_expiracao_senha', sa.DateTime(), nullable=True),
    sa.Column('data_ultimo_acesso', sa.DateTime(), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('bloqueado', sa.Boolean(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('usuario_criacao', sa.Integer(), nullable=False),
    sa.Column('data_alteracao', sa.DateTime(), nullable=True),
    sa.Column('usuario_alteracao', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('cargo_usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_usuario_id', sa.Integer(), nullable=False),
    sa.Column('fk_cargo_id', sa.Integer(), nullable=False),
    sa.Column('fk_usuario_superior_id', sa.Integer(), nullable=True),
    sa.Column('convite', sa.SmallInteger(), nullable=False),
    sa.Column('data_convite_aceito', sa.DateTime(), nullable=True),
    sa.Column('usuario_convite_aceito', sa.Integer(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('usuario_criacao', sa.Integer(), nullable=False),
    sa.Column('data_alteracao', sa.DateTime(), nullable=True),
    sa.Column('usuario_alteracao', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_cargo_id'], ['cargo.id'], ),
    sa.ForeignKeyConstraint(['fk_usuario_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['fk_usuario_superior_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_pais_id', sa.Integer(), nullable=False),
    sa.Column('cod', sa.String(length=5), nullable=False),
    sa.Column('nome', sa.String(length=40), nullable=False),
    sa.Column('nacional', sa.Boolean(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('usuario_criacao', sa.Integer(), nullable=False),
    sa.Column('data_alteracao', sa.DateTime(), nullable=True),
    sa.Column('usuario_alteracao', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_pais_id'], ['pais.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('menu_sistema',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_sistema_id', sa.Integer(), nullable=True),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('menu', sa.String(length=255), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('usuario_criacao', sa.Integer(), nullable=False),
    sa.Column('data_alteracao', sa.DateTime(), nullable=True),
    sa.Column('usuario_alteracao', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_sistema_id'], ['sistema.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('perfil',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_sistema_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=45), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('usuario_criacao', sa.Integer(), nullable=False),
    sa.Column('data_alteracao', sa.DateTime(), nullable=True),
    sa.Column('usuario_alteracao', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_sistema_id'], ['sistema.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('municipio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_estado_id', sa.Integer(), nullable=False),
    sa.Column('nome_municipio', sa.String(length=40), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('usuario_criacao', sa.Integer(), nullable=False),
    sa.Column('data_alteracao', sa.DateTime(), nullable=True),
    sa.Column('usuario_alteracao', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_estado_id'], ['estado.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permissao_menu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_perfil_id', sa.Integer(), nullable=True),
    sa.Column('fk_menu_id', sa.Integer(), nullable=True),
    sa.Column('acessar', sa.SmallInteger(), nullable=True),
    sa.Column('criar', sa.SmallInteger(), nullable=True),
    sa.Column('editar', sa.SmallInteger(), nullable=True),
    sa.Column('deletar', sa.SmallInteger(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('usuario_criacao', sa.Integer(), nullable=False),
    sa.Column('data_alteracao', sa.DateTime(), nullable=True),
    sa.Column('usuario_alteracao', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_menu_id'], ['menu_sistema.id'], ),
    sa.ForeignKeyConstraint(['fk_perfil_id'], ['perfil.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_num_banco', sa.String(length=3), nullable=False),
    sa.Column('fk_municipio_id', sa.Integer(), nullable=True),
    sa.Column('fk_estado_id', sa.Integer(), nullable=True),
    sa.Column('fk_pais_id', sa.Integer(), nullable=True),
    sa.Column('num_agencia', sa.String(length=6), nullable=False),
    sa.Column('nome', sa.String(length=60), nullable=True),
    sa.Column('nome_reduzido', sa.String(length=20), nullable=True),
    sa.Column('numero_oficial', sa.String(length=3), nullable=False),
    sa.Column('digito_banco', sa.String(length=1), nullable=True),
    sa.Column('rua', sa.String(length=100), nullable=True),
    sa.Column('numero', sa.String(length=8), nullable=True),
    sa.Column('complemento', sa.String(length=60), nullable=True),
    sa.Column('bairro', sa.String(length=80), nullable=True),
    sa.Column('cidade', sa.String(length=32), nullable=True),
    sa.Column('cep', sa.String(length=9), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('usuario_criacao', sa.Integer(), nullable=False),
    sa.Column('data_alteracao', sa.DateTime(), nullable=True),
    sa.Column('usuario_alteracao', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_estado_id'], ['estado.id'], ),
    sa.ForeignKeyConstraint(['fk_municipio_id'], ['municipio.id'], ),
    sa.ForeignKeyConstraint(['fk_num_banco'], ['banco.num_banco'], ),
    sa.ForeignKeyConstraint(['fk_pais_id'], ['pais.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agencia', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agencia_num_agencia'), ['num_agencia'], unique=True)

    op.create_table('empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_municipio_id', sa.Integer(), nullable=False),
    sa.Column('nome_fantasia', sa.String(length=255), nullable=False),
    sa.Column('razao_social', sa.String(length=255), nullable=False),
    sa.Column('cnpj', sa.String(length=20), nullable=False),
    sa.Column('inscricao_estadual', sa.String(length=20), nullable=True),
    sa.Column('telefone1', sa.String(length=15), nullable=False),
    sa.Column('telefone2', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('rua', sa.String(length=100), nullable=True),
    sa.Column('numero', sa.String(length=8), nullable=True),
    sa.Column('complemento', sa.String(length=60), nullable=True),
    sa.Column('bairro', sa.String(length=80), nullable=True),
    sa.Column('pais', sa.String(length=20), nullable=True),
    sa.Column('cep', sa.String(length=9), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('usuario_criacao', sa.Integer(), nullable=False),
    sa.Column('data_alteracao', sa.DateTime(), nullable=True),
    sa.Column('usuario_alteracao', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_municipio_id'], ['municipio.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj'),
    sa.UniqueConstraint('email')
    )
    op.create_table('campanha',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_empresa_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.UnicodeText(), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=True),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('valor_meta', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('prorrogado', sa.Integer(), nullable=True),
    sa.Column('data_prorrogacao', sa.Date(), nullable=True),
    sa.Column('valor_total_atingido', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('data_fechamento_campanha', sa.Date(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('usuario_criacao', sa.Integer(), nullable=False),
    sa.Column('data_alteracao', sa.DateTime(), nullable=True),
    sa.Column('usuario_alteracao', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_empresa_id'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categoria_produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_empresa_id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=50), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('usuario_criacao', sa.Integer(), nullable=False),
    sa.Column('data_alteracao', sa.DateTime(), nullable=True),
    sa.Column('usuario_alteracao', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_empresa_id'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('classificacao_financeira',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_classificacao_financeira', sa.String(length=25), nullable=False),
    sa.Column('fk_empresa_id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=40), nullable=False),
    sa.Column('permite_lancamento', sa.Boolean(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('usuario_criacao', sa.Integer(), nullable=False),
    sa.Column('data_alteracao', sa.DateTime(), nullable=True),
    sa.Column('usuario_alteracao', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_empresa_id'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('classificacao_financeira', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_classificacao_financeira_id_classificacao_financeira'), ['id_classificacao_financeira'], unique=True)

    op.create_table('conta_corrente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_empresa_id', sa.Integer(), nullable=False),
    sa.Column('fk_num_banco', sa.String(length=3), nullable=False),
    sa.Column('fk_num_agencia', sa.String(length=6), nullable=False),
    sa.Column('num_conta', sa.String(length=6), nullable=False),
    sa.Column('digito_conta', sa.String(length=2), nullable=True),
    sa.Column('tipo_conta', sa.SmallInteger(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('usuario_criacao', sa.Integer(), nullable=False),
    sa.Column('data_alteracao', sa.DateTime(), nullable=True),
    sa.Column('usuario_alteracao', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_empresa_id'], ['empresa.id'], ),
    sa.ForeignKeyConstraint(['fk_num_agencia'], ['agencia.num_agencia'], ),
    sa.ForeignKeyConstraint(['fk_num_banco'], ['banco.num_banco'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('num_conta')
    )
    op.create_table('filial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_empresa_id', sa.Integer(), nullable=False),
    sa.Column('fk_municipio_id', sa.Integer(), nullable=False),
    sa.Column('nome_fantasia', sa.String(length=255), nullable=True),
    sa.Column('razao_social', sa.String(length=255), nullable=True),
    sa.Column('cnpj', sa.String(length=20), nullable=False),
    sa.Column('inscricao_estadual', sa.String(length=20), nullable=True),
    sa.Column('inscricao_municipal', sa.String(length=20), nullable=True),
    sa.Column('num_reg_junta', sa.String(length=20), nullable=True),
    sa.Column('data_reg_junta', sa.Date(), nullable=True),
    sa.Column('cod_atividade_principal', sa.String(length=20), nullable=True),
    sa.Column('desc_atividade_principal', sa.String(length=200), nullable=True),
    sa.Column('telefone1', sa.String(length=15), nullable=True),
    sa.Column('telefone2', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=60), nullable=False),
    sa.Column('rua', sa.String(length=100), nullable=True),
    sa.Column('numero', sa.String(length=8), nullable=True),
    sa.Column('complemento', sa.String(length=60), nullable=True),
    sa.Column('bairro', sa.String(length=80), nullable=True),
    sa.Column('cep', sa.String(length=9), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('usuario_criacao', sa.Integer(), nullable=False),
    sa.Column('data_alteracao', sa.DateTime(), nullable=True),
    sa.Column('usuario_alteracao', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_empresa_id'], ['empresa.id'], ),
    sa.ForeignKeyConstraint(['fk_municipio_id'], ['municipio.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj'),
    sa.UniqueConstraint('email')
    )
    op.create_table('forma_pagamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_empresa_id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=40), nullable=True),
    sa.Column('tipo_forma_pagamento', sa.SmallInteger(), nullable=True),
    sa.Column('taxa_admin', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('taxa_admin_parc', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('usuario_criacao', sa.Integer(), nullable=False),
    sa.Column('data_alteracao', sa.DateTime(), nullable=True),
    sa.Column('usuario_alteracao', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_empresa_id'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gateway_pagamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_empresa_id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=40), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('merchant_id', sa.String(length=20), nullable=True),
    sa.Column('merchant_key', sa.String(length=80), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('usuario_criacao', sa.Integer(), nullable=False),
    sa.Column('data_alteracao', sa.DateTime(), nullable=True),
    sa.Column('usuario_alteracao', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_empresa_id'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permissao_usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_empresa_id', sa.Integer(), nullable=True),
    sa.Column('fk_usuario_id', sa.Integer(), nullable=True),
    sa.Column('fk_sistema_id', sa.Integer(), nullable=True),
    sa.Column('fk_perfil_id', sa.Integer(), nullable=True),
    sa.Column('super_user', sa.SmallInteger(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('usuario_criacao', sa.Integer(), nullable=False),
    sa.Column('data_alteracao', sa.DateTime(), nullable=True),
    sa.Column('usuario_alteracao', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_empresa_id'], ['empresa.id'], ),
    sa.ForeignKeyConstraint(['fk_perfil_id'], ['perfil.id'], ),
    sa.ForeignKeyConstraint(['fk_sistema_id'], ['sistema.id'], ),
    sa.ForeignKeyConstraint(['fk_usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipo_clifor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_empresa_id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=40), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('usuario_criacao', sa.Integer(), nullable=False),
    sa.Column('data_alteracao', sa.DateTime(), nullable=True),
    sa.Column('usuario_alteracao', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_empresa_id'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipo_documento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_empresa_id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=40), nullable=True),
    sa.Column('ultimo_numero', sa.String(length=20), nullable=True),
    sa.Column('serie_documento', sa.String(length=8), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('usuario_criacao', sa.Integer(), nullable=False),
    sa.Column('data_alteracao', sa.DateTime(), nullable=True),
    sa.Column('usuario_alteracao', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_empresa_id'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carteira',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cod_carteira', sa.String(length=10), nullable=False),
    sa.Column('fk_empresa_id', sa.Integer(), nullable=False),
    sa.Column('fk_filial_id', sa.Integer(), nullable=False),
    sa.Column('fk_num_banco', sa.String(length=3), nullable=False),
    sa.Column('fk_num_agencia', sa.String(length=6), nullable=False),
    sa.Column('fk_num_conta', sa.String(length=6), nullable=False),
    sa.Column('descricao', sa.String(length=100), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('saldo_inicial', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('database_saldo', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('saldo_nao_compensado', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('usuario_criacao', sa.Integer(), nullable=False),
    sa.Column('data_alteracao', sa.DateTime(), nullable=True),
    sa.Column('usuario_alteracao', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_empresa_id'], ['empresa.id'], ),
    sa.ForeignKeyConstraint(['fk_filial_id'], ['filial.id'], ),
    sa.ForeignKeyConstraint(['fk_num_agencia'], ['agencia.num_agencia'], ),
    sa.ForeignKeyConstraint(['fk_num_banco'], ['banco.num_banco'], ),
    sa.ForeignKeyConstraint(['fk_num_conta'], ['conta_corrente.num_conta'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('carteira', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_carteira_cod_carteira'), ['cod_carteira'], unique=True)

    op.create_table('chave_pix',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_empresa_id', sa.Integer(), nullable=False),
    sa.Column('fk_num_banco', sa.String(length=3), nullable=False),
    sa.Column('fk_num_agencia', sa.String(length=6), nullable=False),
    sa.Column('fk_num_conta', sa.String(length=6), nullable=False),
    sa.Column('chave', sa.String(length=100), nullable=True),
    sa.Column('tipo_chave', sa.SmallInteger(), nullable=True),
    sa.Column('principal', sa.SmallInteger(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('cedente', sa.String(length=50), nullable=True),
    sa.Column('cnpj_cedente', sa.String(length=20), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('usuario_criacao', sa.Integer(), nullable=False),
    sa.Column('data_alteracao', sa.DateTime(), nullable=True),
    sa.Column('usuario_alteracao', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_empresa_id'], ['empresa.id'], ),
    sa.ForeignKeyConstraint(['fk_num_agencia'], ['agencia.num_agencia'], ),
    sa.ForeignKeyConstraint(['fk_num_banco'], ['banco.num_banco'], ),
    sa.ForeignKeyConstraint(['fk_num_conta'], ['conta_corrente.num_conta'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clifor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_empresa_id', sa.Integer(), nullable=False),
    sa.Column('fk_municipio_id', sa.Integer(), nullable=True),
    sa.Column('fk_tipo_clifor_id', sa.Integer(), nullable=True),
    sa.Column('fk_usuario_id', sa.Integer(), nullable=True),
    sa.Column('tipo_clifor', sa.String(length=1), nullable=False),
    sa.Column('nome_fantasia', sa.String(length=100), nullable=True),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('pf_pj', sa.String(length=1), nullable=True),
    sa.Column('cpf_cnpj', sa.String(length=20), nullable=True),
    sa.Column('telefone1', sa.String(length=15), nullable=True),
    sa.Column('telefone2', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('sexo', sa.String(length=20), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('usuario_criacao', sa.Integer(), nullable=False),
    sa.Column('data_alteracao', sa.DateTime(), nullable=True),
    sa.Column('usuario_alteracao', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_empresa_id'], ['empresa.id'], ),
    sa.ForeignKeyConstraint(['fk_municipio_id'], ['municipio.id'], ),
    sa.ForeignKeyConstraint(['fk_tipo_clifor_id'], ['tipo_clifor.id'], ),
    sa.ForeignKeyConstraint(['fk_usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf_cnpj'),
    sa.UniqueConstraint('email')
    )
    op.create_table('convenio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_empresa_id', sa.Integer(), nullable=False),
    sa.Column('fk_num_banco', sa.String(length=3), nullable=False),
    sa.Column('fk_num_agencia', sa.String(length=6), nullable=False),
    sa.Column('fk_num_conta', sa.String(length=6), nullable=False),
    sa.Column('convenio', sa.String(length=20), nullable=True),
    sa.Column('digito_convenio', sa.String(length=2), nullable=True),
    sa.Column('carteira', sa.String(length=3), nullable=True),
    sa.Column('tipo_carteira', sa.SmallInteger(), nullable=True),
    sa.Column('cedente', sa.String(length=50), nullable=True),
    sa.Column('cnpj_cedente', sa.String(length=20), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('usuario_criacao', sa.Integer(), nullable=False),
    sa.Column('data_alteracao', sa.DateTime(), nullable=True),
    sa.Column('usuario_alteracao', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_empresa_id'], ['empresa.id'], ),
    sa.ForeignKeyConstraint(['fk_num_agencia'], ['agencia.num_agencia'], ),
    sa.ForeignKeyConstraint(['fk_num_banco'], ['banco.num_banco'], ),
    sa.ForeignKeyConstraint(['fk_num_conta'], ['conta_corrente.num_conta'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_empresa_id', sa.Integer(), nullable=False),
    sa.Column('fk_categoria_produto_id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=50), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('usuario_criacao', sa.Integer(), nullable=False),
    sa.Column('data_alteracao', sa.DateTime(), nullable=True),
    sa.Column('usuario_alteracao', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_categoria_produto_id'], ['categoria_produto.id'], ),
    sa.ForeignKeyConstraint(['fk_empresa_id'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('boleto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_empresa_id', sa.Integer(), nullable=False),
    sa.Column('fk_carteira_cod', sa.String(length=10), nullable=False),
    sa.Column('fk_convenio_id', sa.Integer(), nullable=False),
    sa.Column('fk_filial_id', sa.Integer(), nullable=False),
    sa.Column('fk_clifor_id', sa.Integer(), nullable=False),
    sa.Column('status_boleto', sa.SmallInteger(), nullable=False),
    sa.Column('status_cnab', sa.SmallInteger(), nullable=True),
    sa.Column('comando_cnab', sa.SmallInteger(), nullable=True),
    sa.Column('data_emissao', sa.DateTime(), nullable=False),
    sa.Column('data_vencimento', sa.DateTime(), nullable=False),
    sa.Column('data_cancelamento', sa.DateTime(), nullable=True),
    sa.Column('valor_boleto', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('valor_baixado', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('valor_desconto', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('juros_ao_dia', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('valor_juros', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('valor_multa', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('codigo_barra', sa.String(length=45), nullable=True),
    sa.Column('ipte', sa.String(length=48), nullable=True),
    sa.Column('nosso_numero', sa.String(length=20), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('usuario_criacao', sa.Integer(), nullable=False),
    sa.Column('data_alteracao', sa.DateTime(), nullable=True),
    sa.Column('usuario_alteracao', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_carteira_cod'], ['carteira.cod_carteira'], ),
    sa.ForeignKeyConstraint(['fk_clifor_id'], ['clifor.id'], ),
    sa.ForeignKeyConstraint(['fk_convenio_id'], ['convenio.id'], ),
    sa.ForeignKeyConstraint(['fk_empresa_id'], ['empresa.id'], ),
    sa.ForeignKeyConstraint(['fk_filial_id'], ['filial.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('endereco',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_clifor_id', sa.Integer(), nullable=False),
    sa.Column('rua', sa.String(length=100), nullable=True),
    sa.Column('numero', sa.String(length=8), nullable=True),
    sa.Column('complemento', sa.String(length=60), nullable=True),
    sa.Column('bairro', sa.String(length=80), nullable=True),
    sa.Column('cidade', sa.String(length=32), nullable=True),
    sa.Column('estado', sa.String(length=80), nullable=True),
    sa.Column('cep', sa.String(length=9), nullable=True),
    sa.Column('obriga_atualizar_endereco', sa.Boolean(), nullable=True),
    sa.Column('ultima_atualizacao_endereco', sa.Date(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('usuario_criacao', sa.Integer(), nullable=False),
    sa.Column('data_alteracao', sa.DateTime(), nullable=True),
    sa.Column('usuario_alteracao', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_clifor_id'], ['clifor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_empresa_id', sa.Integer(), nullable=False),
    sa.Column('fk_filial_id', sa.Integer(), nullable=False),
    sa.Column('fk_clifor_id', sa.Integer(), nullable=False),
    sa.Column('fk_campanha_id', sa.Integer(), nullable=False),
    sa.Column('fk_forma_pagamento_id', sa.Integer(), nullable=False),
    sa.Column('data_pedido', sa.DateTime(), nullable=True),
    sa.Column('periodicidade', sa.SmallInteger(), nullable=False),
    sa.Column('status_pedido', sa.SmallInteger(), nullable=True),
    sa.Column('valor_total_pedido', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('order_id', sa.String(length=100), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('usuario_criacao', sa.Integer(), nullable=False),
    sa.Column('data_alteracao', sa.DateTime(), nullable=True),
    sa.Column('usuario_alteracao', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_campanha_id'], ['campanha.id'], ),
    sa.ForeignKeyConstraint(['fk_clifor_id'], ['clifor.id'], ),
    sa.ForeignKeyConstraint(['fk_empresa_id'], ['empresa.id'], ),
    sa.ForeignKeyConstraint(['fk_filial_id'], ['filial.id'], ),
    sa.ForeignKeyConstraint(['fk_forma_pagamento_id'], ['forma_pagamento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_empresa_id', sa.Integer(), nullable=False),
    sa.Column('fk_produto_id', sa.Integer(), nullable=False),
    sa.Column('fk_pedido_id', sa.Integer(), nullable=False),
    sa.Column('data_pedido', sa.DateTime(), nullable=True),
    sa.Column('quantidade', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('valor', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('usuario_criacao', sa.Integer(), nullable=False),
    sa.Column('data_alteracao', sa.DateTime(), nullable=True),
    sa.Column('usuario_alteracao', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_empresa_id'], ['empresa.id'], ),
    sa.ForeignKeyConstraint(['fk_pedido_id'], ['pedido.id'], ),
    sa.ForeignKeyConstraint(['fk_produto_id'], ['produto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lancamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_empresa_id', sa.Integer(), nullable=False),
    sa.Column('fk_filial_id', sa.Integer(), nullable=False),
    sa.Column('fk_clifor_id', sa.Integer(), nullable=False),
    sa.Column('fk_tipo_documento_id', sa.Integer(), nullable=False),
    sa.Column('fk_sistema_id', sa.Integer(), nullable=False),
    sa.Column('fk_carteira_cod', sa.String(length=10), nullable=False),
    sa.Column('fk_boleto_id', sa.Integer(), nullable=True),
    sa.Column('natureza', sa.String(length=1), nullable=False),
    sa.Column('numero_documento', sa.String(length=40), nullable=False),
    sa.Column('serie_documento', sa.String(length=8), nullable=True),
    sa.Column('status_lancamento', sa.SmallInteger(), nullable=False),
    sa.Column('id_processo', sa.Integer(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_emissao', sa.DateTime(), nullable=False),
    sa.Column('data_vencimento', sa.DateTime(), nullable=False),
    sa.Column('data_previsao_baixa', sa.DateTime(), nullable=True),
    sa.Column('data_baixa', sa.DateTime(), nullable=True),
    sa.Column('data_cancelamento', sa.DateTime(), nullable=True),
    sa.Column('historico', sa.String(length=255), nullable=True),
    sa.Column('mes_competencia', sa.DateTime(), nullable=True),
    sa.Column('valor_original', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('valor_baixado', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('valor_juros', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('valor_multa', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('codigo_barra', sa.String(length=45), nullable=True),
    sa.Column('ipte', sa.String(length=48), nullable=True),
    sa.Column('nosso_numero_cnab', sa.String(length=20), nullable=True),
    sa.Column('numero_parcela', sa.Integer(), nullable=True),
    sa.Column('id_classific_financ', sa.String(length=25), nullable=True),
    sa.Column('usuario_criacao', sa.Integer(), nullable=False),
    sa.Column('data_alteracao', sa.DateTime(), nullable=True),
    sa.Column('usuario_alteracao', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_boleto_id'], ['boleto.id'], ),
    sa.ForeignKeyConstraint(['fk_carteira_cod'], ['carteira.cod_carteira'], ),
    sa.ForeignKeyConstraint(['fk_clifor_id'], ['clifor.id'], ),
    sa.ForeignKeyConstraint(['fk_empresa_id'], ['empresa.id'], ),
    sa.ForeignKeyConstraint(['fk_filial_id'], ['filial.id'], ),
    sa.ForeignKeyConstraint(['fk_sistema_id'], ['sistema.id'], ),
    sa.ForeignKeyConstraint(['fk_tipo_documento_id'], ['tipo_documento.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_documento')
    )
    op.create_table('boleto_lancamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_empresa_id', sa.Integer(), nullable=False),
    sa.Column('fk_lancamento_id', sa.Integer(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('usuario_criacao', sa.Integer(), nullable=False),
    sa.Column('data_alteracao', sa.DateTime(), nullable=True),
    sa.Column('usuario_alteracao', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_empresa_id'], ['empresa.id'], ),
    sa.ForeignKeyConstraint(['fk_lancamento_id'], ['lancamento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extrato_financeiro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_empresa_id', sa.Integer(), nullable=False),
    sa.Column('fk_filial_id', sa.Integer(), nullable=False),
    sa.Column('fk_carteira_cod', sa.String(length=10), nullable=False),
    sa.Column('fk_lancamento_id', sa.Integer(), nullable=False),
    sa.Column('fk_forma_pagamento_id', sa.Integer(), nullable=False),
    sa.Column('numero_documento', sa.String(length=40), nullable=False),
    sa.Column('tipo', sa.SmallInteger(), nullable=False),
    sa.Column('status_extrato', sa.SmallInteger(), nullable=False),
    sa.Column('status_conciliacao', sa.SmallInteger(), nullable=False),
    sa.Column('historico', sa.String(length=255), nullable=True),
    sa.Column('data_baixa', sa.DateTime(), nullable=False),
    sa.Column('data_cancelamento_baixa', sa.DateTime(), nullable=True),
    sa.Column('valor', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('data_extrato', sa.DateTime(), nullable=False),
    sa.Column('data_vencimento', sa.DateTime(), nullable=True),
    sa.Column('data_compensacao', sa.DateTime(), nullable=True),
    sa.Column('data_cancelamento', sa.DateTime(), nullable=True),
    sa.Column('data_estorno', sa.DateTime(), nullable=True),
    sa.Column('status_concil_cartao', sa.SmallInteger(), nullable=True),
    sa.Column('cartao_operadora', sa.Integer(), nullable=True),
    sa.Column('cartao_bandeira', sa.Integer(), nullable=True),
    sa.Column('cartao_nsu', sa.String(length=50), nullable=True),
    sa.Column('cartao_tid', sa.String(length=50), nullable=True),
    sa.Column('cartao_autorizacao', sa.String(length=50), nullable=True),
    sa.Column('cartao_numero_parcela', sa.Integer(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('usuario_criacao', sa.Integer(), nullable=False),
    sa.Column('data_alteracao', sa.DateTime(), nullable=True),
    sa.Column('usuario_alteracao', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_carteira_cod'], ['carteira.cod_carteira'], ),
    sa.ForeignKeyConstraint(['fk_empresa_id'], ['empresa.id'], ),
    sa.ForeignKeyConstraint(['fk_filial_id'], ['filial.id'], ),
    sa.ForeignKeyConstraint(['fk_forma_pagamento_id'], ['forma_pagamento.id'], ),
    sa.ForeignKeyConstraint(['fk_lancamento_id'], ['lancamento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('processamento_pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_empresa_id', sa.Integer(), nullable=False),
    sa.Column('fk_filial_id', sa.Integer(), nullable=False),
    sa.Column('fk_pedido_id', sa.Integer(), nullable=False),
    sa.Column('fk_clifor_id', sa.Integer(), nullable=False),
    sa.Column('fk_forma_pagamento_id', sa.Integer(), nullable=False),
    sa.Column('fk_lancamento_id', sa.Integer(), nullable=True),
    sa.Column('data_processamento', sa.DateTime(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('status_processamento', sa.SmallInteger(), nullable=True),
    sa.Column('id_transacao_gateway', sa.String(length=255), nullable=True),
    sa.Column('transaction_id', sa.String(length=100), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('usuario_criacao', sa.Integer(), nullable=False),
    sa.Column('data_alteracao', sa.DateTime(), nullable=True),
    sa.Column('usuario_alteracao', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_clifor_id'], ['clifor.id'], ),
    sa.ForeignKeyConstraint(['fk_empresa_id'], ['empresa.id'], ),
    sa.ForeignKeyConstraint(['fk_filial_id'], ['filial.id'], ),
    sa.ForeignKeyConstraint(['fk_forma_pagamento_id'], ['forma_pagamento.id'], ),
    sa.ForeignKeyConstraint(['fk_lancamento_id'], ['lancamento.id'], ),
    sa.ForeignKeyConstraint(['fk_pedido_id'], ['pedido.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('baixa_lancamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_empresa_id', sa.Integer(), nullable=False),
    sa.Column('fk_lancamento_id', sa.Integer(), nullable=False),
    sa.Column('fk_forma_pagamento_id', sa.Integer(), nullable=False),
    sa.Column('fk_extrato_financeiro_id', sa.Integer(), nullable=True),
    sa.Column('fk_carteira_cod', sa.String(length=10), nullable=False),
    sa.Column('data_baixa', sa.DateTime(), nullable=False),
    sa.Column('data_cancelamento_baixa', sa.DateTime(), nullable=True),
    sa.Column('valor_baixa', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('valor_original', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('valor_desconto', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('valor_juros', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('valor_multa', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('status_baixa', sa.SmallInteger(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('usuario_criacao', sa.Integer(), nullable=False),
    sa.Column('data_alteracao', sa.DateTime(), nullable=True),
    sa.Column('usuario_alteracao', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_carteira_cod'], ['carteira.cod_carteira'], ),
    sa.ForeignKeyConstraint(['fk_empresa_id'], ['empresa.id'], ),
    sa.ForeignKeyConstraint(['fk_extrato_financeiro_id'], ['extrato_financeiro.id'], ),
    sa.ForeignKeyConstraint(['fk_forma_pagamento_id'], ['forma_pagamento.id'], ),
    sa.ForeignKeyConstraint(['fk_lancamento_id'], ['lancamento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('baixa_lancamento')
    op.drop_table('processamento_pedido')
    op.drop_table('extrato_financeiro')
    op.drop_table('boleto_lancamento')
    op.drop_table('lancamento')
    op.drop_table('item_pedido')
    op.drop_table('pedido')
    op.drop_table('endereco')
    op.drop_table('boleto')
    op.drop_table('produto')
    op.drop_table('convenio')
    op.drop_table('clifor')
    op.drop_table('chave_pix')
    with op.batch_alter_table('carteira', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_carteira_cod_carteira'))

    op.drop_table('carteira')
    op.drop_table('tipo_documento')
    op.drop_table('tipo_clifor')
    op.drop_table('permissao_usuario')
    op.drop_table('gateway_pagamento')
    op.drop_table('forma_pagamento')
    op.drop_table('filial')
    op.drop_table('conta_corrente')
    with op.batch_alter_table('classificacao_financeira', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_classificacao_financeira_id_classificacao_financeira'))

    op.drop_table('classificacao_financeira')
    op.drop_table('categoria_produto')
    op.drop_table('campanha')
    op.drop_table('empresa')
    with op.batch_alter_table('agencia', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agencia_num_agencia'))

    op.drop_table('agencia')
    op.drop_table('permissao_menu')
    op.drop_table('municipio')
    op.drop_table('perfil')
    op.drop_table('menu_sistema')
    op.drop_table('estado')
    op.drop_table('cargo_usuario')
    op.drop_table('usuario')
    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tokens_token'))

    op.drop_table('tokens')
    op.drop_table('sistema')
    op.drop_table('pais')
    op.drop_table('cargo')
    with op.batch_alter_table('banco', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_banco_num_banco'))

    op.drop_table('banco')
    # ### end Alembic commands ###
