"""create: criado tabelas projeto agape

Revision ID: bd96af13b2f3
Revises: 955df075f8e0
Create Date: 2024-10-29 14:55:06.642039

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = "bd96af13b2f3"
down_revision = "955df075f8e0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "estoque_agape",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("item", sa.String(length=100), nullable=False),
        sa.Column("quantidade", sa.Integer(), nullable=False),
        sa.Column("criado_em", sa.DateTime(), nullable=True),
        sa.Column("atualizado_em", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("estoque_agape", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_estoque_agape_criado_em"), ["criado_em"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_estoque_agape_item"), ["item"], unique=False
        )

    op.create_table(
        "aquisicao_agape",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fk_estoque_agape_id", sa.Integer(), nullable=False),
        sa.Column("quantidade", sa.Integer(), nullable=False),
        sa.Column("data_aquisicao", sa.DateTime(), nullable=False),
        sa.Column("criado_em", sa.DateTime(), nullable=True),
        sa.Column("atualizado_em", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["fk_estoque_agape_id"],
            ["estoque_agape.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("aquisicao_agape", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_aquisicao_agape_data_aquisicao"),
            ["data_aquisicao"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_aquisicao_agape_fk_estoque_agape_id"),
            ["fk_estoque_agape_id"],
            unique=False,
        )

    op.create_table(
        "acao_agape",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fk_endereco_id", sa.Integer(), nullable=True),
        sa.Column("fk_estoque_agape_id", sa.Integer(), nullable=False),
        sa.Column("quantidade", sa.Integer(), nullable=False),
        sa.Column("criado_em", sa.DateTime(), nullable=True),
        sa.Column("atualizado_em", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["fk_endereco_id"],
            ["endereco.id"],
        ),
        sa.ForeignKeyConstraint(
            ["fk_estoque_agape_id"],
            ["estoque_agape.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("acao_agape", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_acao_agape_criado_em"), ["criado_em"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_acao_agape_fk_endereco_id"), ["fk_endereco_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_acao_agape_fk_estoque_agape_id"),
            ["fk_estoque_agape_id"],
            unique=False,
        )

    op.create_table(
        "familia_agape",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fk_endereco_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.Boolean(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("criado_em", sa.DateTime(), nullable=True),
        sa.Column("atualizado_em", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["fk_endereco_id"],
            ["endereco.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("familia_agape", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_familia_agape_criado_em"), ["criado_em"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_familia_agape_fk_endereco_id"),
            ["fk_endereco_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_familia_agape_status"), ["status"], unique=False
        )

    op.create_table(
        "doacao_agape",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fk_estoque_agape_id", sa.Integer(), nullable=False),
        sa.Column("fk_familia_agape_id", sa.Integer(), nullable=False),
        sa.Column("fk_acao_agape_id", sa.Integer(), nullable=True),
        sa.Column("quantidade", sa.Integer(), nullable=False),
        sa.Column("data_doacao", sa.DateTime(), nullable=False),
        sa.Column("criado_em", sa.DateTime(), nullable=True),
        sa.Column("atualizado_em", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["fk_acao_agape_id"],
            ["acao_agape.id"],
        ),
        sa.ForeignKeyConstraint(
            ["fk_estoque_agape_id"],
            ["estoque_agape.id"],
        ),
        sa.ForeignKeyConstraint(
            ["fk_familia_agape_id"],
            ["familia_agape.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("doacao_agape", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_doacao_agape_data_doacao"), ["data_doacao"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_doacao_agape_fk_acao_agape_id"),
            ["fk_acao_agape_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_doacao_agape_fk_estoque_agape_id"),
            ["fk_estoque_agape_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_doacao_agape_fk_familia_agape_id"),
            ["fk_familia_agape_id"],
            unique=False,
        )

    op.create_table(
        "membro_agape",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fk_familia_agape_id", sa.Integer(), nullable=False),
        sa.Column("responsavel", sa.Boolean(), nullable=True),
        sa.Column("nome", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=True),
        sa.Column("telefone", sa.String(length=20), nullable=True),
        sa.Column("cpf", sa.String(length=14), nullable=True),
        sa.Column("data_nascimento", sa.Date(), nullable=False),
        sa.Column("funcao_familiar", sa.String(length=50), nullable=False),
        sa.Column("escolaridade", sa.String(length=50), nullable=False),
        sa.Column("ocupacao", sa.String(length=100), nullable=False),
        sa.Column("renda", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("criado_em", sa.DateTime(), nullable=True),
        sa.Column("atualizado_em", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["fk_familia_agape_id"],
            ["familia_agape.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("membro_agape", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_membro_agape_cpf"), ["cpf"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_membro_agape_data_nascimento"),
            ["data_nascimento"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_membro_agape_fk_familia_agape_id"),
            ["fk_familia_agape_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_membro_agape_responsavel"), ["responsavel"], unique=False
        )

    op.create_table(
        "programacao_acao_agape",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fk_acao_agape_id", sa.Integer(), nullable=False),
        sa.Column("data_acao", sa.DateTime(), nullable=False),
        sa.Column("criado_em", sa.DateTime(), nullable=True),
        sa.Column("atualizado_em", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["fk_acao_agape_id"],
            ["acao_agape.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("programacao_acao_agape", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_programacao_acao_agape_data_acao"),
            ["data_acao"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_programacao_acao_agape_fk_acao_agape_id"),
            ["fk_acao_agape_id"],
            unique=False,
        )

    op.create_table(
        "recibo_agape",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fk_doacao_agape_id", sa.Integer(), nullable=True),
        sa.Column("recibo", sa.String(length=100), nullable=True),
        sa.Column("criado_em", sa.DateTime(), nullable=True),
        sa.Column("atualizado_em", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["fk_doacao_agape_id"],
            ["doacao_agape.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("recibo_agape", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_recibo_agape_fk_doacao_agape_id"),
            ["fk_doacao_agape_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("recibo_agape", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_recibo_agape_fk_doacao_agape_id"))

    op.drop_table("recibo_agape")
    with op.batch_alter_table("programacao_acao_agape", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_programacao_acao_agape_fk_acao_agape_id"))
        batch_op.drop_index(batch_op.f("ix_programacao_acao_agape_data_acao"))

    op.drop_table("programacao_acao_agape")
    with op.batch_alter_table("membro_agape", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_membro_agape_responsavel"))
        batch_op.drop_index(batch_op.f("ix_membro_agape_fk_familia_agape_id"))
        batch_op.drop_index(batch_op.f("ix_membro_agape_data_nascimento"))
        batch_op.drop_index(batch_op.f("ix_membro_agape_cpf"))

    op.drop_table("membro_agape")
    with op.batch_alter_table("doacao_agape", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_doacao_agape_fk_familia_agape_id"))
        batch_op.drop_index(batch_op.f("ix_doacao_agape_fk_estoque_agape_id"))
        batch_op.drop_index(batch_op.f("ix_doacao_agape_fk_acao_agape_id"))
        batch_op.drop_index(batch_op.f("ix_doacao_agape_data_doacao"))

    op.drop_table("doacao_agape")
    with op.batch_alter_table("familia_agape", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_familia_agape_status"))
        batch_op.drop_index(batch_op.f("ix_familia_agape_fk_endereco_id"))
        batch_op.drop_index(batch_op.f("ix_familia_agape_criado_em"))

    op.drop_table("familia_agape")
    with op.batch_alter_table("acao_agape", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_acao_agape_fk_estoque_agape_id"))
        batch_op.drop_index(batch_op.f("ix_acao_agape_fk_endereco_id"))
        batch_op.drop_index(batch_op.f("ix_acao_agape_criado_em"))

    op.drop_table("acao_agape")
    with op.batch_alter_table("aquisicao_agape", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_aquisicao_agape_fk_estoque_agape_id"))
        batch_op.drop_index(batch_op.f("ix_aquisicao_agape_data_aquisicao"))

    op.drop_table("aquisicao_agape")
    with op.batch_alter_table("estoque_agape", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_estoque_agape_item"))
        batch_op.drop_index(batch_op.f("ix_estoque_agape_criado_em"))

    op.drop_table("estoque_agape")
    # ### end Alembic commands ###
