"""Alter_table_vocacional

Revision ID: c59032348c0e
Revises: 6867458897d5
Create Date: 2024-11-06 16:57:24.861615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c59032348c0e'
down_revision = '6867458897d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cadastro_vocacional', schema=None) as batch_op:
        batch_op.alter_column(
            'fk_pre_cadastro_id',
            existing_type=sa.INTEGER(),
            nullable=False
        )
        batch_op.create_unique_constraint('uq_fk_pre_cadastro_id', ['fk_pre_cadastro_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cadastro_vocacional', schema=None) as batch_op:
        batch_op.drop_constraint('uq_fk_pre_cadastro_id', type_='unique')
        batch_op.alter_column(
            'fk_pre_cadastro_id',
            existing_type=sa.INTEGER(),
            nullable=True
        )
    # ### end Alembic commands ###
