"""removing-depends-empresa-id

Revision ID: c73b64e95561
Revises: 0a5d5f53b68d
Create Date: 2024-11-26 22:06:47.982752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c73b64e95561'
down_revision = '0a5d5f53b68d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campanha', schema=None) as batch_op:
        batch_op.alter_column('fk_empresa_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('forma_pagamento', schema=None) as batch_op:
        batch_op.alter_column('fk_empresa_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forma_pagamento', schema=None) as batch_op:
        batch_op.alter_column('fk_empresa_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('campanha', schema=None) as batch_op:
        batch_op.alter_column('fk_empresa_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
