"""alter table mensageria

Revision ID: c7a36fd36622
Revises: dd6cae1d8835
Create Date: 2025-01-28 12:52:53.800879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7a36fd36622'
down_revision = 'dd6cae1d8835'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mensageria', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=15, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=25),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mensageria', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=25),
               type_=sa.VARCHAR(length=15, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)

    # ### end Alembic commands ###
