"""atualizando migrations

Revision ID: c838fafbbe9f
Revises: 4c3efc965d98
Create Date: 2024-04-04 16:25:00.873000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c838fafbbe9f'
down_revision = '4c3efc965d98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    ...

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('campanha_origem')

    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.alter_column('id',
                              existing_type=sa.Integer(),
                              type_=sa.BIGINT(),
                              existing_nullable=False,
                              autoincrement=True,
                              existing_server_default=sa.Identity(always=False, start=1, increment=1))

    with op.batch_alter_table('landpage_users', schema=None) as batch_op:
        batch_op.alter_column('registered_at',
                              existing_type=sa.DATETIME(),
                              nullable=False)
        batch_op.alter_column('campaign_id',
                              existing_type=sa.INTEGER(),
                              nullable=False)
        batch_op.alter_column('landpage_id',
                              existing_type=sa.INTEGER(),
                              nullable=False)

    with op.batch_alter_table('landpage', schema=None) as batch_op:
        batch_op.alter_column('type',
                              existing_type=sa.INTEGER(),
                              nullable=False,
                              existing_server_default=sa.text("('1')"))

    op.drop_table('log_logradouro')
    op.drop_table('log_localidade')
    op.drop_table('log_bairro')
    # ### end Alembic commands ###
