"""Add Column Status In Table Generais

Revision ID: cdddabb2d4ff
Revises: d3bee1cc660d
Create Date: 2025-01-16 17:02:25.528100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdddabb2d4ff'
down_revision = 'd3bee1cc660d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generais', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generais', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
