"""create_table_generais

Revision ID: cdeb3ae604e7
Revises: 13a454ed79fb
Create Date: 2024-09-23 16:48:23.896087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdeb3ae604e7'
down_revision = '13a454ed79fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.Column('quant_membros_grupo', sa.Integer(), nullable=True),
    sa.Column('tempo_de_membro', sa.Integer(), nullable=True),
    sa.Column('print_grupo', sa.String(), nullable=True),
    sa.Column('vinculo_marechal', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('usuario_alteracao', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['vinculo_marechal'], ['cargo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('generais')
    # ### end Alembic commands ###
