"""remove-fk_empresa_id-and-tipo_clifor-from-clifor

Revision ID: d36cf86627e0
Revises: 8f372bf12ee4
Create Date: 2024-11-22 11:36:46.544506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd36cf86627e0'
down_revision = '8f372bf12ee4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clifor', schema=None) as batch_op:
        batch_op.alter_column('fk_empresa_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('tipo_clifor',
               existing_type=sa.VARCHAR(length=1, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clifor', schema=None) as batch_op:
        batch_op.alter_column('tipo_clifor',
               existing_type=sa.VARCHAR(length=1, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
        batch_op.alter_column('fk_empresa_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
