"""add-id-pagamento-proc-pedido

Revision ID: d39a6ea95aa7
Revises: 7ed4c045aed3
Create Date: 2024-08-27 17:20:43.349223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd39a6ea95aa7'
down_revision = '7ed4c045aed3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processamento_pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_pagamento', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processamento_pedido', schema=None) as batch_op:
        batch_op.drop_column('id_pagamento')

    # ### end Alembic commands ###
