"""Alter Table Generais

Revision ID: d3bee1cc660d
Revises: 7fc2de3ab213
Create Date: 2025-01-16 12:22:00.340068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3bee1cc660d'
down_revision = '7fc2de3ab213'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generais', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link_grupo', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('nome_grupo', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('tempo_de_administrador', sa.Integer(), nullable=True))
        batch_op.drop_column('tempo_de_membro')
        batch_op.drop_column('print_grupo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generais', schema=None) as batch_op:
        batch_op.add_column(sa.Column('print_grupo', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tempo_de_membro', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('tempo_de_administrador')
        batch_op.drop_column('nome_grupo')
        batch_op.drop_column('link_grupo')

    # ### end Alembic commands ###
