"""create_table_cadastro_vocacional

Revision ID: d663617096e8
Revises: 30b2195d04c2
Create Date: 2024-08-23 16:38:46.317868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd663617096e8'
down_revision = '30b2195d04c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cadastro_vocacional',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_pre_cadastro_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('desistencia_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_por', sa.Integer(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fk_pre_cadastro_id'], ['pre_cadastro_vocacional.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cadastro_vocacional')
    # ### end Alembic commands ###
