"""Alter_table_Evento_Usuario

Revision ID: d97366b52240
Revises: e2ac6b8d9ed7
Create Date: 2024-06-11 10:02:56.481283

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = 'd97366b52240'
down_revision = 'e2ac6b8d9ed7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evento_usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('presencas', sa.Integer(), nullable=False))
        batch_op.drop_column('presenca')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evento_usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('presenca', mssql.BIT(), autoincrement=False, nullable=False))
        batch_op.drop_column('presencas')

    # ### end Alembic commands ###
