"""add-coluna-gateway-pagamento-em-pedidos

Revision ID: e2ac6b8d9ed7
Revises: f544efb184fb
Create Date: 2024-06-03 14:46:54.027551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2ac6b8d9ed7'
down_revision = 'f544efb184fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fk_gateway_pagamento_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'gateway_pagamento', ['fk_gateway_pagamento_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('fk_gateway_pagamento_id')

    # ### end Alembic commands ###
