"""add: campanhas action_leads/zone zone_id

Revision ID: e3e17fb6c293
Revises: 898ff235b279
Create Date: 2024-10-07 15:07:35.660341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3e17fb6c293'
down_revision = '898ff235b279'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actions_leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zone', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('zone_id', sa.String(length=40), nullable=True))

    with op.batch_alter_table('campanha', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zone', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('zone_id', sa.String(length=40), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campanha', schema=None) as batch_op:
        batch_op.drop_column('zone_id')
        batch_op.drop_column('zone')

    with op.batch_alter_table('actions_leads', schema=None) as batch_op:
        batch_op.drop_column('zone_id')
        batch_op.drop_column('zone')

    # ### end Alembic commands ###
