"""convert-data-criacao-to-datetime

Revision ID: e5ff39903db8
Revises: 1aa2cc1086b6
Create Date: 2024-08-13 12:42:24.714425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5ff39903db8'
down_revision = '1aa2cc1086b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_imports', schema=None) as batch_op:
        batch_op.alter_column('data_criacao',
               existing_type=sa.VARCHAR(length=2000, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.DateTime(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_imports', schema=None) as batch_op:
        batch_op.alter_column('data_criacao',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=2000, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)

    # ### end Alembic commands ###
