"""add: processamento_pedido/contabilizar_doacao

Revision ID: e84c6b686783
Revises: 5caddcd5eab2
Create Date: 2024-09-23 09:36:17.391777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e84c6b686783'
down_revision = '5caddcd5eab2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processamento_pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contabilizar_doacao', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processamento_pedido', schema=None) as batch_op:
        batch_op.drop_column('contabilizar_doacao')

    # ### end Alembic commands ###
