"""atualizando migrations

Revision ID: e990db62b627
Revises: c838fafbbe9f
Create Date: 2024-04-04 16:27:36.017561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e990db62b627'
down_revision = 'c838fafbbe9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    ...

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('campanha_origem')

    with op.batch_alter_table('landpage_users', schema=None) as batch_op:
        batch_op.alter_column('registered_at',
                              existing_type=sa.DATETIME(),
                              nullable=False)
        batch_op.alter_column('campaign_id',
                              existing_type=sa.INTEGER(),
                              nullable=False)
        batch_op.alter_column('landpage_id',
                              existing_type=sa.INTEGER(),
                              nullable=False)

    with op.batch_alter_table('landpage', schema=None) as batch_op:
        batch_op.alter_column('type',
                              existing_type=sa.INTEGER(),
                              nullable=False,
                              existing_server_default=sa.text("('1')"))

    op.drop_table('log_logradouro')
    op.drop_table('log_localidade')
    op.drop_table('log_bairro')
    # ### end Alembic commands ###
