"""foto-para-campanha

Revision ID: ed7772fa9f44
Revises: 8d2b808d3d46
Create Date: 2024-06-21 12:01:50.510918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed7772fa9f44'
down_revision = '8d2b808d3d46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campanha', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preenchimento_foto', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('label_foto', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campanha', schema=None) as batch_op:
        batch_op.drop_column('label_foto')
        batch_op.drop_column('preenchimento_foto')

    # ### end Alembic commands ###
