"""table generais adicionado contraint

Revision ID: edb110e7b33f
Revises: b4173705bb7b
Create Date: 2025-03-26 22:21:30.919972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edb110e7b33f'
down_revision = 'b4173705bb7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generais', schema=None) as batch_op:
        batch_op.drop_index('ix_generais_fk_usuario_id')
        batch_op.create_index(batch_op.f('ix_generais_fk_usuario_id'), ['fk_usuario_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generais', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generais_fk_usuario_id'))
        batch_op.create_index('ix_generais_fk_usuario_id', ['fk_usuario_id'], unique=False)

    # ### end Alembic commands ###
