"""Create_Table_Tipo_Email

Revision ID: ee5b9f7f33d5
Revises: 9d5a0c93cb39
Create Date: 2024-10-30 16:04:09.102985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee5b9f7f33d5'
down_revision = '9d5a0c93cb39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipo_email',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('tipo_email', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tipo_email_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tipo_email', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tipo_email_id'))

    op.drop_table('tipo_email')
    # ### end Alembic commands ###
