"""alter table endereco

Revision ID: f00ceecec0d8
Revises: 2e2b534fc738
Create Date: 2025-01-23 10:31:55.717973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f00ceecec0d8'
down_revision = '2e2b534fc738'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('endereco', schema=None) as batch_op:
        batch_op.drop_constraint('FK__endereco__fk_gen__0C70CFB4', type_='foreignkey')
        batch_op.drop_column('fk_general_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('endereco', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fk_general_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('FK__endereco__fk_gen__0C70CFB4', 'generais', ['fk_general_id'], ['id'])

    # ### end Alembic commands ###
