"""Fix_Update_table_historico_campaign

Revision ID: f544efb184fb
Revises: 7b2eac8477ca
Create Date: 2024-06-03 13:56:14.247886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f544efb184fb'
down_revision = '7b2eac8477ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historico_campanha_doacoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_alteracao', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historico_campanha_doacoes', schema=None) as batch_op:
        batch_op.drop_column('data_alteracao')

    # ### end Alembic commands ###
