"""criacao-tabela-leads-sorteados

Revision ID: f5d9b6f304ea
Revises: 8ae3267d604c
Create Date: 2024-08-20 15:23:11.724467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5d9b6f304ea'
down_revision = '8ae3267d604c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads_sorteados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('data_sorteio', sa.DateTime(), nullable=True),
    sa.Column('sorteador', sa.Integer(), nullable=True),
    sa.Column('acao_sorteada', sa.Integer(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['acao_sorteada'], ['actions_leads.id'], ),
    sa.ForeignKeyConstraint(['sorteador'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('leads_sorteados')
    # ### end Alembic commands ###
