"""Create_Table_Send_Emails_Inactives

Revision ID: f725c96bb641
Revises: 953e093dcf57
Create Date: 2024-05-15 09:25:23.572169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f725c96bb641'
down_revision = '953e093dcf57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('send_emails_inactives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_send', sa.String(), nullable=False),
    sa.Column('send_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('send_emails_inactives')
    # ### end Alembic commands ###
