"""empty message

Revision ID: fb24475b02ab
Revises: b05868157641
Create Date: 2023-10-20 09:17:11.736780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb24475b02ab'
down_revision = 'b05868157641'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.alter_column('fk_filial_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('processamento_pedido', schema=None) as batch_op:
        batch_op.alter_column('fk_filial_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processamento_pedido', schema=None) as batch_op:
        batch_op.alter_column('fk_filial_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.alter_column('fk_filial_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
