"""add-nome_familia-na-tabela-familia_agape

Revision ID: fbf3be8e167a
Revises: c59032348c0e
Create Date: 2024-11-07 13:58:34.052437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbf3be8e167a'
down_revision = 'c59032348c0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('familia_agape', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome_familia', sa.String(length=100), nullable=False))
        batch_op.create_index(batch_op.f('ix_familia_agape_nome_familia'), ['nome_familia'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('familia_agape', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_familia_agape_nome_familia'))
        batch_op.drop_column('nome_familia')

    # ### end Alembic commands ###