"""alter_table_users_imports_add_updated_at

Revision ID: fcc9ce5a2bb8
Revises: 510c81c5fe9c
Create Date: 2024-07-31 14:06:07.626194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcc9ce5a2bb8'
down_revision = '510c81c5fe9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_imports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_imports', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
