"""alter_table_endereco

Revision ID: fe5b599e299b
Revises: 3f1f66a480b6
Create Date: 2024-08-23 17:20:57.176846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe5b599e299b'
down_revision = '3f1f66a480b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('endereco', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fk_cadastro_vocacional_id', sa.Integer(), nullable=True))
        batch_op.alter_column('fk_clifor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'cadastro_vocacional', ['fk_cadastro_vocacional_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('endereco', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('fk_clifor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('fk_cadastro_vocacional_id')

    # ### end Alembic commands ###
