"""Update_table_pedidos_de_oracao

Revision ID: fe9087c92df1
Revises: 96fdf79005eb
Create Date: 2024-06-18 11:16:15.098046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe9087c92df1'
down_revision = '96fdf79005eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos_de_oracao', schema=None) as batch_op:
        batch_op.alter_column('local_realizacao',
               existing_type=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos_de_oracao', schema=None) as batch_op:
        batch_op.alter_column('local_realizacao',
               existing_type=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)

    # ### end Alembic commands ###
