"""alterando-table-view-recorrentes

Revision ID: fec424444f1e
Revises: 14a0e04317e0
Create Date: 2024-07-26 14:16:35.813355

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = 'fec424444f1e'
down_revision = '14a0e04317e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('view_recorrentes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_hora_inicio', sa.Time(), nullable=False))
        batch_op.add_column(sa.Column('data_hora_fim', sa.Time(), nullable=False))
        batch_op.drop_column('hora_fim')
        batch_op.drop_column('hora_inicio')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('view_recorrentes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hora_inicio', mssql.TIME(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('hora_fim', mssql.TIME(), autoincrement=False, nullable=False))
        batch_op.drop_column('data_hora_fim')
        batch_op.drop_column('data_hora_inicio')

    # ### end Alembic commands ###
